// Code generated by protoc-gen-go.
// source: pp.account.proto
// DO NOT EDIT!

package pp

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type CreateAccountReq struct {
	Pubkey           *string `protobuf:"bytes,10,opt,name=pubkey" json:"pubkey,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *CreateAccountReq) Reset()                    { *m = CreateAccountReq{} }
func (m *CreateAccountReq) String() string            { return proto.CompactTextString(m) }
func (*CreateAccountReq) ProtoMessage()               {}
func (*CreateAccountReq) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{0} }

func (m *CreateAccountReq) GetPubkey() string {
	if m != nil && m.Pubkey != nil {
		return *m.Pubkey
	}
	return ""
}

type CreateAccountRes struct {
	Result           *Result `protobuf:"bytes,1,req,name=result" json:"result,omitempty"`
	Pubkey           *string `protobuf:"bytes,10,opt,name=pubkey" json:"pubkey,omitempty"`
	CreatedAt        *int64  `protobuf:"varint,20,opt,name=created_at" json:"created_at,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *CreateAccountRes) Reset()                    { *m = CreateAccountRes{} }
func (m *CreateAccountRes) String() string            { return proto.CompactTextString(m) }
func (*CreateAccountRes) ProtoMessage()               {}
func (*CreateAccountRes) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{1} }

func (m *CreateAccountRes) GetResult() *Result {
	if m != nil {
		return m.Result
	}
	return nil
}

func (m *CreateAccountRes) GetPubkey() string {
	if m != nil && m.Pubkey != nil {
		return *m.Pubkey
	}
	return ""
}

func (m *CreateAccountRes) GetCreatedAt() int64 {
	if m != nil && m.CreatedAt != nil {
		return *m.CreatedAt
	}
	return 0
}

func init() {
	proto.RegisterType((*CreateAccountReq)(nil), "pp.CreateAccountReq")
	proto.RegisterType((*CreateAccountRes)(nil), "pp.CreateAccountRes")
}

func init() { proto.RegisterFile("pp.account.proto", fileDescriptor2) }

var fileDescriptor2 = []byte{
	// 140 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xe2, 0x12, 0x28, 0x28, 0xd0, 0x4b,
	0x4c, 0x4e, 0xce, 0x2f, 0xcd, 0x2b, 0xd1, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x2a, 0x28,
	0x90, 0xe2, 0x2f, 0x28, 0xd0, 0x4b, 0xce, 0xcf, 0xcd, 0xcd, 0xcf, 0x83, 0x08, 0x2a, 0x29, 0x71,
	0x09, 0x38, 0x17, 0xa5, 0x26, 0x96, 0xa4, 0x3a, 0x42, 0xd4, 0x06, 0xa5, 0x16, 0x0a, 0xf1, 0x71,
	0xb1, 0x15, 0x94, 0x26, 0x65, 0xa7, 0x56, 0x4a, 0x70, 0x29, 0x30, 0x6a, 0x70, 0x2a, 0x05, 0x61,
	0xa8, 0x29, 0x16, 0x92, 0xe2, 0x62, 0x2b, 0x4a, 0x2d, 0x2e, 0xcd, 0x29, 0x91, 0x60, 0x54, 0x60,
	0xd2, 0xe0, 0x36, 0xe2, 0xd2, 0x2b, 0x28, 0xd0, 0x0b, 0x02, 0x8b, 0xa0, 0xeb, 0x17, 0x12, 0xe2,
	0xe2, 0x4a, 0x06, 0xeb, 0x4f, 0x89, 0x4f, 0x2c, 0x91, 0x10, 0x51, 0x60, 0xd4, 0x60, 0x06, 0x04,
	0x00, 0x00, 0xff, 0xff, 0xaf, 0xad, 0x53, 0x4e, 0x9f, 0x00, 0x00, 0x00,
}
