// Code generated by protoc-gen-go.
// source: pp.admin.proto
// DO NOT EDIT!

package pp

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type UpdateCreditReq struct {
	Pubkey           *string `protobuf:"bytes,10,opt,name=pubkey" json:"pubkey,omitempty"`
	CoinType         *string `protobuf:"bytes,20,opt,name=coin_type" json:"coin_type,omitempty"`
	Credit           *uint64 `protobuf:"varint,30,opt,name=credit" json:"credit,omitempty"`
	DstPubkey        *string `protobuf:"bytes,40,opt,name=dst_pubkey" json:"dst_pubkey,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *UpdateCreditReq) Reset()                    { *m = UpdateCreditReq{} }
func (m *UpdateCreditReq) String() string            { return proto.CompactTextString(m) }
func (*UpdateCreditReq) ProtoMessage()               {}
func (*UpdateCreditReq) Descriptor() ([]byte, []int) { return fileDescriptor11, []int{0} }

func (m *UpdateCreditReq) GetPubkey() string {
	if m != nil && m.Pubkey != nil {
		return *m.Pubkey
	}
	return ""
}

func (m *UpdateCreditReq) GetCoinType() string {
	if m != nil && m.CoinType != nil {
		return *m.CoinType
	}
	return ""
}

func (m *UpdateCreditReq) GetCredit() uint64 {
	if m != nil && m.Credit != nil {
		return *m.Credit
	}
	return 0
}

func (m *UpdateCreditReq) GetDstPubkey() string {
	if m != nil && m.DstPubkey != nil {
		return *m.DstPubkey
	}
	return ""
}

type UpdateCreditRes struct {
	Result           *Result `protobuf:"bytes,1,req,name=result" json:"result,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *UpdateCreditRes) Reset()                    { *m = UpdateCreditRes{} }
func (m *UpdateCreditRes) String() string            { return proto.CompactTextString(m) }
func (*UpdateCreditRes) ProtoMessage()               {}
func (*UpdateCreditRes) Descriptor() ([]byte, []int) { return fileDescriptor11, []int{1} }

func (m *UpdateCreditRes) GetResult() *Result {
	if m != nil {
		return m.Result
	}
	return nil
}

func init() {
	proto.RegisterType((*UpdateCreditReq)(nil), "pp.UpdateCreditReq")
	proto.RegisterType((*UpdateCreditRes)(nil), "pp.UpdateCreditRes")
}

func init() { proto.RegisterFile("pp.admin.proto", fileDescriptor11) }

var fileDescriptor11 = []byte{
	// 159 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xe2, 0xe2, 0x2b, 0x28, 0xd0, 0x4b,
	0x4c, 0xc9, 0xcd, 0xcc, 0xd3, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x2a, 0x28, 0x90, 0xe2,
	0x07, 0x8a, 0x25, 0xe7, 0xe7, 0xe6, 0xe6, 0x43, 0x05, 0x95, 0x22, 0xb8, 0xf8, 0x43, 0x0b, 0x52,
	0x12, 0x4b, 0x52, 0x9d, 0x8b, 0x52, 0x53, 0x32, 0x4b, 0x82, 0x52, 0x0b, 0x85, 0xf8, 0xb8, 0xd8,
	0x0a, 0x4a, 0x93, 0xb2, 0x53, 0x2b, 0x25, 0xb8, 0x14, 0x18, 0x35, 0x38, 0x85, 0x04, 0xb9, 0x38,
	0x93, 0xf3, 0x33, 0xf3, 0xe2, 0x4b, 0x2a, 0x0b, 0x52, 0x25, 0x44, 0xc0, 0x42, 0x40, 0x25, 0xc9,
	0x60, 0xf5, 0x12, 0x72, 0x40, 0x3e, 0x8b, 0x90, 0x10, 0x17, 0x57, 0x4a, 0x71, 0x49, 0x3c, 0x54,
	0x9b, 0x06, 0x48, 0x8d, 0x92, 0x2e, 0xba, 0xc9, 0xc5, 0x42, 0x52, 0x5c, 0x6c, 0x45, 0xa9, 0xc5,
	0xa5, 0x39, 0x25, 0x12, 0x8c, 0x0a, 0x4c, 0x1a, 0xdc, 0x46, 0x5c, 0x7a, 0x40, 0xe7, 0x04, 0x81,
	0x45, 0x00, 0x01, 0x00, 0x00, 0xff, 0xff, 0x56, 0x56, 0x46, 0xcc, 0xae, 0x00, 0x00, 0x00,
}
