// Code generated by protoc-gen-go.
// source: pp.balance.proto
// DO NOT EDIT!

package pp

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// Balance the both skycoin and bitcoin have amount field,
// while the hours will be omited when used as bitcoin balance.
type Balance struct {
	Amount           *uint64 `protobuf:"varint,10,opt,name=amount" json:"amount,omitempty"`
	Hours            *uint64 `protobuf:"varint,11,opt,name=hours" json:"hours,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *Balance) Reset()                    { *m = Balance{} }
func (m *Balance) String() string            { return proto.CompactTextString(m) }
func (*Balance) ProtoMessage()               {}
func (*Balance) Descriptor() ([]byte, []int) { return fileDescriptor5, []int{0} }

func (m *Balance) GetAmount() uint64 {
	if m != nil && m.Amount != nil {
		return *m.Amount
	}
	return 0
}

func (m *Balance) GetHours() uint64 {
	if m != nil && m.Hours != nil {
		return *m.Hours
	}
	return 0
}

type GetAccountBalanceReq struct {
	Pubkey           *string `protobuf:"bytes,10,opt,name=pubkey" json:"pubkey,omitempty"`
	CoinType         *string `protobuf:"bytes,11,opt,name=coin_type" json:"coin_type,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *GetAccountBalanceReq) Reset()                    { *m = GetAccountBalanceReq{} }
func (m *GetAccountBalanceReq) String() string            { return proto.CompactTextString(m) }
func (*GetAccountBalanceReq) ProtoMessage()               {}
func (*GetAccountBalanceReq) Descriptor() ([]byte, []int) { return fileDescriptor5, []int{1} }

func (m *GetAccountBalanceReq) GetPubkey() string {
	if m != nil && m.Pubkey != nil {
		return *m.Pubkey
	}
	return ""
}

func (m *GetAccountBalanceReq) GetCoinType() string {
	if m != nil && m.CoinType != nil {
		return *m.CoinType
	}
	return ""
}

type GetAccountBalanceRes struct {
	Result           *Result  `protobuf:"bytes,1,req,name=result" json:"result,omitempty"`
	Balance          *Balance `protobuf:"bytes,12,opt,name=balance" json:"balance,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *GetAccountBalanceRes) Reset()                    { *m = GetAccountBalanceRes{} }
func (m *GetAccountBalanceRes) String() string            { return proto.CompactTextString(m) }
func (*GetAccountBalanceRes) ProtoMessage()               {}
func (*GetAccountBalanceRes) Descriptor() ([]byte, []int) { return fileDescriptor5, []int{2} }

func (m *GetAccountBalanceRes) GetResult() *Result {
	if m != nil {
		return m.Result
	}
	return nil
}

func (m *GetAccountBalanceRes) GetBalance() *Balance {
	if m != nil {
		return m.Balance
	}
	return nil
}

type GetAddrBalanceReq struct {
	CoinType         *string `protobuf:"bytes,10,opt,name=coin_type" json:"coin_type,omitempty"`
	Addrs            *string `protobuf:"bytes,20,opt,name=addrs" json:"addrs,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *GetAddrBalanceReq) Reset()                    { *m = GetAddrBalanceReq{} }
func (m *GetAddrBalanceReq) String() string            { return proto.CompactTextString(m) }
func (*GetAddrBalanceReq) ProtoMessage()               {}
func (*GetAddrBalanceReq) Descriptor() ([]byte, []int) { return fileDescriptor5, []int{3} }

func (m *GetAddrBalanceReq) GetCoinType() string {
	if m != nil && m.CoinType != nil {
		return *m.CoinType
	}
	return ""
}

func (m *GetAddrBalanceReq) GetAddrs() string {
	if m != nil && m.Addrs != nil {
		return *m.Addrs
	}
	return ""
}

type GetAddrBalanceRes struct {
	Result           *Result  `protobuf:"bytes,1,req,name=result" json:"result,omitempty"`
	Balance          *Balance `protobuf:"bytes,10,opt,name=balance" json:"balance,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *GetAddrBalanceRes) Reset()                    { *m = GetAddrBalanceRes{} }
func (m *GetAddrBalanceRes) String() string            { return proto.CompactTextString(m) }
func (*GetAddrBalanceRes) ProtoMessage()               {}
func (*GetAddrBalanceRes) Descriptor() ([]byte, []int) { return fileDescriptor5, []int{4} }

func (m *GetAddrBalanceRes) GetResult() *Result {
	if m != nil {
		return m.Result
	}
	return nil
}

func (m *GetAddrBalanceRes) GetBalance() *Balance {
	if m != nil {
		return m.Balance
	}
	return nil
}

func init() {
	proto.RegisterType((*Balance)(nil), "pp.Balance")
	proto.RegisterType((*GetAccountBalanceReq)(nil), "pp.GetAccountBalanceReq")
	proto.RegisterType((*GetAccountBalanceRes)(nil), "pp.GetAccountBalanceRes")
	proto.RegisterType((*GetAddrBalanceReq)(nil), "pp.GetAddrBalanceReq")
	proto.RegisterType((*GetAddrBalanceRes)(nil), "pp.GetAddrBalanceRes")
}

func init() { proto.RegisterFile("pp.balance.proto", fileDescriptor5) }

var fileDescriptor5 = []byte{
	// 222 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x8c, 0x8e, 0x3d, 0x4f, 0xc3, 0x30,
	0x10, 0x86, 0x95, 0x8a, 0xb6, 0xca, 0x99, 0x02, 0xb5, 0x3a, 0x58, 0x15, 0x43, 0xe4, 0xc9, 0x93,
	0x87, 0x4a, 0x0c, 0x8c, 0xb0, 0x30, 0x21, 0xa1, 0xfe, 0x01, 0xe4, 0xda, 0x96, 0x40, 0x34, 0xf6,
	0xe1, 0x8f, 0x21, 0xff, 0x1e, 0xd9, 0xc9, 0x00, 0x0a, 0x43, 0xc7, 0x7b, 0xef, 0x7d, 0xee, 0x1e,
	0xb8, 0x43, 0x94, 0x27, 0x75, 0x56, 0x4e, 0x5b, 0x89, 0xc1, 0x27, 0x4f, 0x17, 0x88, 0xfb, 0x5b,
	0x44, 0xa9, 0x7d, 0xdf, 0x7b, 0x37, 0x86, 0x5c, 0xc0, 0xfa, 0x79, 0x6c, 0xd1, 0x1b, 0x58, 0xa9,
	0xde, 0x67, 0x97, 0x18, 0x74, 0x8d, 0xb8, 0xa2, 0x1b, 0x58, 0x7e, 0xf8, 0x1c, 0x22, 0x23, 0x65,
	0xe4, 0x8f, 0xb0, 0x7b, 0xb1, 0xe9, 0x49, 0xeb, 0x52, 0x99, 0x98, 0xa3, 0xfd, 0x2e, 0x18, 0xe6,
	0xd3, 0x97, 0x1d, 0x2a, 0xd6, 0xd2, 0x2d, 0xb4, 0xda, 0x7f, 0xba, 0xf7, 0x34, 0xa0, 0xad, 0x68,
	0xcb, 0xdf, 0xfe, 0x45, 0x23, 0xdd, 0xc3, 0x2a, 0xd8, 0x98, 0xcf, 0x89, 0x35, 0xdd, 0x42, 0x90,
	0x03, 0x48, 0x44, 0x79, 0xac, 0x09, 0xbd, 0x87, 0xf5, 0xa4, 0xcf, 0xae, 0xbb, 0x46, 0x90, 0x03,
	0x29, 0xcb, 0x09, 0xe6, 0x0f, 0xb0, 0x2d, 0x17, 0x8d, 0x09, 0xbf, 0x4c, 0xfe, 0x7c, 0x1e, 0x65,
	0x36, 0xb0, 0x54, 0xc6, 0x84, 0xc8, 0x76, 0x55, 0xe4, 0x75, 0x8e, 0x5d, 0x6c, 0x01, 0x33, 0x8b,
	0x9f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x45, 0xa9, 0x54, 0x71, 0x64, 0x01, 0x00, 0x00,
}
