// Code generated by protoc-gen-go.
// source: pp.balance.proto
// DO NOT EDIT!

package pp

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type GetBalanceReq struct {
	AccountId        *string `protobuf:"bytes,10,opt,name=account_id" json:"account_id,omitempty"`
	CoinType         *string `protobuf:"bytes,11,opt,name=coin_type" json:"coin_type,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *GetBalanceReq) Reset()                    { *m = GetBalanceReq{} }
func (m *GetBalanceReq) String() string            { return proto.CompactTextString(m) }
func (*GetBalanceReq) ProtoMessage()               {}
func (*GetBalanceReq) Descriptor() ([]byte, []int) { return fileDescriptor5, []int{0} }

func (m *GetBalanceReq) GetAccountId() string {
	if m != nil && m.AccountId != nil {
		return *m.AccountId
	}
	return ""
}

func (m *GetBalanceReq) GetCoinType() string {
	if m != nil && m.CoinType != nil {
		return *m.CoinType
	}
	return ""
}

type GetBalanceRes struct {
	Result           *Result `protobuf:"bytes,1,req,name=result" json:"result,omitempty"`
	AccountId        *string `protobuf:"bytes,10,opt,name=account_id" json:"account_id,omitempty"`
	CoinType         *string `protobuf:"bytes,11,opt,name=coin_type" json:"coin_type,omitempty"`
	Balance          *uint64 `protobuf:"varint,12,opt,name=balance" json:"balance,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *GetBalanceRes) Reset()                    { *m = GetBalanceRes{} }
func (m *GetBalanceRes) String() string            { return proto.CompactTextString(m) }
func (*GetBalanceRes) ProtoMessage()               {}
func (*GetBalanceRes) Descriptor() ([]byte, []int) { return fileDescriptor5, []int{1} }

func (m *GetBalanceRes) GetResult() *Result {
	if m != nil {
		return m.Result
	}
	return nil
}

func (m *GetBalanceRes) GetAccountId() string {
	if m != nil && m.AccountId != nil {
		return *m.AccountId
	}
	return ""
}

func (m *GetBalanceRes) GetCoinType() string {
	if m != nil && m.CoinType != nil {
		return *m.CoinType
	}
	return ""
}

func (m *GetBalanceRes) GetBalance() uint64 {
	if m != nil && m.Balance != nil {
		return *m.Balance
	}
	return 0
}

func init() {
	proto.RegisterType((*GetBalanceReq)(nil), "pp.GetBalanceReq")
	proto.RegisterType((*GetBalanceRes)(nil), "pp.GetBalanceRes")
}

func init() { proto.RegisterFile("pp.balance.proto", fileDescriptor5) }

var fileDescriptor5 = []byte{
	// 150 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xe2, 0x12, 0x28, 0x28, 0xd0, 0x4b,
	0x4a, 0xcc, 0x49, 0xcc, 0x4b, 0x4e, 0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x2a, 0x28,
	0x90, 0xe2, 0x07, 0x8a, 0x26, 0xe7, 0xe7, 0xe6, 0xe6, 0xe7, 0x41, 0x04, 0x95, 0xcc, 0xb8, 0x78,
	0xdd, 0x53, 0x4b, 0x9c, 0x20, 0x0a, 0x83, 0x52, 0x0b, 0x85, 0x84, 0xb8, 0xb8, 0x12, 0x93, 0x93,
	0xf3, 0x4b, 0xf3, 0x4a, 0xe2, 0x33, 0x53, 0x24, 0xb8, 0x14, 0x18, 0x35, 0x38, 0x85, 0x04, 0xb9,
	0x38, 0x93, 0xf3, 0x33, 0xf3, 0xe2, 0x4b, 0x2a, 0x0b, 0x52, 0x25, 0xb8, 0x41, 0x42, 0x4a, 0xc9,
	0xa8, 0xfa, 0x8a, 0x85, 0xa4, 0xb8, 0xd8, 0x8a, 0x52, 0x8b, 0x4b, 0x73, 0x4a, 0x24, 0x18, 0x15,
	0x98, 0x34, 0xb8, 0x8d, 0xb8, 0xf4, 0x80, 0x56, 0x05, 0x81, 0x45, 0x88, 0x34, 0x53, 0x88, 0x9f,
	0x8b, 0x1d, 0xea, 0x62, 0x09, 0x1e, 0xa0, 0x00, 0x0b, 0x20, 0x00, 0x00, 0xff, 0xff, 0x53, 0x4e,
	0x49, 0x30, 0xc4, 0x00, 0x00, 0x00,
}
