// Code generated by protoc-gen-go.
// source: pp.content.proto
// DO NOT EDIT!

package pp

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type ContentReq struct {
	AccountId        *string `protobuf:"bytes,1,opt,name=account_id" json:"account_id,omitempty"`
	Nonce            []byte  `protobuf:"bytes,2,opt,name=nonce" json:"nonce,omitempty"`
	Encryptdata      []byte  `protobuf:"bytes,3,opt,name=encryptdata" json:"encryptdata,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *ContentReq) Reset()                    { *m = ContentReq{} }
func (m *ContentReq) String() string            { return proto.CompactTextString(m) }
func (*ContentReq) ProtoMessage()               {}
func (*ContentReq) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{0} }

func (m *ContentReq) GetAccountId() string {
	if m != nil && m.AccountId != nil {
		return *m.AccountId
	}
	return ""
}

func (m *ContentReq) GetNonce() []byte {
	if m != nil {
		return m.Nonce
	}
	return nil
}

func (m *ContentReq) GetEncryptdata() []byte {
	if m != nil {
		return m.Encryptdata
	}
	return nil
}

type ContentRes struct {
	Nonce            []byte `protobuf:"bytes,10,opt,name=nonce" json:"nonce,omitempty"`
	Encryptdata      []byte `protobuf:"bytes,20,opt,name=encryptdata" json:"encryptdata,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *ContentRes) Reset()                    { *m = ContentRes{} }
func (m *ContentRes) String() string            { return proto.CompactTextString(m) }
func (*ContentRes) ProtoMessage()               {}
func (*ContentRes) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{1} }

func (m *ContentRes) GetNonce() []byte {
	if m != nil {
		return m.Nonce
	}
	return nil
}

func (m *ContentRes) GetEncryptdata() []byte {
	if m != nil {
		return m.Encryptdata
	}
	return nil
}

func init() {
	proto.RegisterType((*ContentReq)(nil), "pp.ContentReq")
	proto.RegisterType((*ContentRes)(nil), "pp.ContentRes")
}

func init() { proto.RegisterFile("pp.content.proto", fileDescriptor1) }

var fileDescriptor1 = []byte{
	// 122 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xe2, 0x12, 0x28, 0x28, 0xd0, 0x4b,
	0xce, 0xcf, 0x2b, 0x49, 0xcd, 0x2b, 0xd1, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x2a, 0x28,
	0x50, 0x72, 0xe1, 0xe2, 0x72, 0x86, 0x08, 0x06, 0xa5, 0x16, 0x0a, 0x09, 0x71, 0x71, 0x25, 0x26,
	0x27, 0xe7, 0x97, 0xe6, 0x95, 0xc4, 0x67, 0xa6, 0x48, 0x30, 0x2a, 0x30, 0x6a, 0x70, 0x0a, 0xf1,
	0x72, 0xb1, 0xe6, 0xe5, 0xe7, 0x25, 0xa7, 0x4a, 0x30, 0x01, 0xb9, 0x3c, 0x42, 0xc2, 0x5c, 0xdc,
	0xa9, 0x79, 0xc9, 0x45, 0x95, 0x05, 0x25, 0x29, 0x89, 0x25, 0x89, 0x12, 0xcc, 0x20, 0x41, 0x25,
	0x03, 0x24, 0x53, 0x8a, 0x11, 0x3a, 0xb8, 0xb0, 0xe9, 0x10, 0x01, 0x09, 0x02, 0x02, 0x00, 0x00,
	0xff, 0xff, 0xe6, 0x65, 0x25, 0x0e, 0x8e, 0x00, 0x00, 0x00,
}
