// Code generated by protoc-gen-go.
// source: pp.common.proto
// DO NOT EDIT!

/*
Package pp is a generated protocol buffer package.

It is generated from these files:
	pp.common.proto
	pp.content.proto
	pp.account.proto
	pp.deposit.proto
	pp.withdrawal.proto
	pp.balance.proto

It has these top-level messages:
	Result
	EmptyRes
	ContentReq
	ContentRes
	CreateAccountReq
	CreateAccountRes
	GetDepositAddrReq
	GetDepositAddrRes
	WithdrawalReq
	WithdrawalRes
	GetBalanceReq
	GetBalanceRes
*/
package pp

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type ErrCode int32

const (
	ErrCode_ErrCode_Success     ErrCode = 0
	ErrCode_ErrCode_WrongFormat ErrCode = 10
)

var ErrCode_name = map[int32]string{
	0:  "ErrCode_Success",
	10: "ErrCode_WrongFormat",
}
var ErrCode_value = map[string]int32{
	"ErrCode_Success":     0,
	"ErrCode_WrongFormat": 10,
}

func (x ErrCode) Enum() *ErrCode {
	p := new(ErrCode)
	*p = x
	return p
}
func (x ErrCode) String() string {
	return proto.EnumName(ErrCode_name, int32(x))
}
func (x *ErrCode) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(ErrCode_value, data, "ErrCode")
	if err != nil {
		return err
	}
	*x = ErrCode(value)
	return nil
}
func (ErrCode) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type Result struct {
	Success          *bool   `protobuf:"varint,1,req,name=success" json:"success,omitempty"`
	Code             *int32  `protobuf:"varint,2,opt,name=code" json:"code,omitempty"`
	Reason           *string `protobuf:"bytes,3,opt,name=reason" json:"reason,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *Result) Reset()                    { *m = Result{} }
func (m *Result) String() string            { return proto.CompactTextString(m) }
func (*Result) ProtoMessage()               {}
func (*Result) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Result) GetSuccess() bool {
	if m != nil && m.Success != nil {
		return *m.Success
	}
	return false
}

func (m *Result) GetCode() int32 {
	if m != nil && m.Code != nil {
		return *m.Code
	}
	return 0
}

func (m *Result) GetReason() string {
	if m != nil && m.Reason != nil {
		return *m.Reason
	}
	return ""
}

type EmptyRes struct {
	Result           *Result `protobuf:"bytes,1,req,name=result" json:"result,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *EmptyRes) Reset()                    { *m = EmptyRes{} }
func (m *EmptyRes) String() string            { return proto.CompactTextString(m) }
func (*EmptyRes) ProtoMessage()               {}
func (*EmptyRes) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *EmptyRes) GetResult() *Result {
	if m != nil {
		return m.Result
	}
	return nil
}

func init() {
	proto.RegisterType((*Result)(nil), "pp.Result")
	proto.RegisterType((*EmptyRes)(nil), "pp.EmptyRes")
	proto.RegisterEnum("pp.ErrCode", ErrCode_name, ErrCode_value)
}

func init() { proto.RegisterFile("pp.common.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 169 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xe2, 0xe2, 0x2f, 0x28, 0xd0, 0x4b,
	0xce, 0xcf, 0xcd, 0xcd, 0xcf, 0xd3, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x2a, 0x28, 0x50,
	0x32, 0xe7, 0x62, 0x0b, 0x4a, 0x2d, 0x2e, 0xcd, 0x29, 0x11, 0xe2, 0xe7, 0x62, 0x2f, 0x2e, 0x4d,
	0x4e, 0x4e, 0x2d, 0x2e, 0x96, 0x60, 0x54, 0x60, 0xd2, 0xe0, 0x10, 0xe2, 0xe1, 0x62, 0x49, 0xce,
	0x4f, 0x49, 0x95, 0x60, 0x52, 0x60, 0xd4, 0x60, 0x15, 0xe2, 0xe3, 0x62, 0x2b, 0x4a, 0x4d, 0x2c,
	0xce, 0xcf, 0x93, 0x60, 0x06, 0xf2, 0x39, 0x95, 0xd4, 0xb8, 0x38, 0x5c, 0x73, 0x0b, 0x4a, 0x2a,
	0x81, 0xba, 0x85, 0xa4, 0x40, 0x72, 0x20, 0x43, 0xc0, 0x3a, 0xb9, 0x8d, 0xb8, 0xf4, 0x80, 0x56,
	0x41, 0x8c, 0xd5, 0x32, 0xe7, 0x62, 0x77, 0x2d, 0x2a, 0x72, 0x06, 0x1a, 0x24, 0x24, 0xcc, 0xc5,
	0x0f, 0x65, 0xc6, 0x07, 0x43, 0x6c, 0x12, 0x60, 0x10, 0x12, 0xe7, 0x12, 0x86, 0x09, 0x86, 0x17,
	0xe5, 0xe7, 0xa5, 0xbb, 0xe5, 0x17, 0xe5, 0x26, 0x96, 0x08, 0x70, 0x01, 0x02, 0x00, 0x00, 0xff,
	0xff, 0xd3, 0x6c, 0x6e, 0xac, 0xaf, 0x00, 0x00, 0x00,
}
