// Code generated by protoc-gen-go.
// source: pp.common.proto
// DO NOT EDIT!

/*
Package pp is a generated protocol buffer package.

It is generated from these files:
	pp.common.proto
	pp.encrypt.proto
	pp.account.proto
	pp.deposit.proto
	pp.withdrawal.proto
	pp.balance.proto
	pp.order.proto
	pp.coin.proto
	pp.request.proto
	pp.utxo.proto
	pp.transaction.proto
	pp.admin.proto

It has these top-level messages:
	Result
	EmptyRes
	EncryptReq
	EncryptRes
	CreateAccountReq
	CreateAccountRes
	GetDepositAddrReq
	GetDepositAddrRes
	WithdrawalReq
	WithdrawalRes
	GetBalanceReq
	GetBalanceRes
	OrderReq
	OrderRes
	Order
	GetOrderReq
	GetOrderRes
	GetCoinsReq
	CoinsRes
	Request
	GetUtxoReq
	BtcUtxo
	SkyUtxo
	GetUtxoRes
	InjectTxnReq
	InjectTxnRes
	GetTxReq
	Tx
	GetTxRes
	GetRawTxReq
	GetRawTxRes
	BtcTx
	BtcVin
	BtcScriptSig
	BtcVout
	BtcScriptPubKeyResult
	SkyTx
	SkyTxOutput
	UpdateCreditReq
	UpdateCreditRes
*/
package pp

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type ErrCode int32

const (
	ErrCode_Success         ErrCode = 0
	ErrCode_WrongFormat     ErrCode = 10
	ErrCode_WrongPubkey     ErrCode = 20
	ErrCode_WrongRequest    ErrCode = 21
	ErrCode_UnAuthorized    ErrCode = 31
	ErrCode_NotExits        ErrCode = 32
	ErrCode_AlreadyExits    ErrCode = 33
	ErrCode_ServerError     ErrCode = 40
	ErrCode_BroadcastTxFail ErrCode = 50
)

var ErrCode_name = map[int32]string{
	0:  "Success",
	10: "WrongFormat",
	20: "WrongPubkey",
	21: "WrongRequest",
	31: "UnAuthorized",
	32: "NotExits",
	33: "AlreadyExits",
	40: "ServerError",
	50: "BroadcastTxFail",
}
var ErrCode_value = map[string]int32{
	"Success":         0,
	"WrongFormat":     10,
	"WrongPubkey":     20,
	"WrongRequest":    21,
	"UnAuthorized":    31,
	"NotExits":        32,
	"AlreadyExits":    33,
	"ServerError":     40,
	"BroadcastTxFail": 50,
}

func (x ErrCode) Enum() *ErrCode {
	p := new(ErrCode)
	*p = x
	return p
}
func (x ErrCode) String() string {
	return proto.EnumName(ErrCode_name, int32(x))
}
func (x *ErrCode) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(ErrCode_value, data, "ErrCode")
	if err != nil {
		return err
	}
	*x = ErrCode(value)
	return nil
}
func (ErrCode) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type Result struct {
	Success          *bool   `protobuf:"varint,1,req,name=success" json:"success,omitempty"`
	Errcode          *int32  `protobuf:"varint,2,opt,name=errcode" json:"errcode,omitempty"`
	Reason           *string `protobuf:"bytes,3,opt,name=reason" json:"reason,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *Result) Reset()                    { *m = Result{} }
func (m *Result) String() string            { return proto.CompactTextString(m) }
func (*Result) ProtoMessage()               {}
func (*Result) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Result) GetSuccess() bool {
	if m != nil && m.Success != nil {
		return *m.Success
	}
	return false
}

func (m *Result) GetErrcode() int32 {
	if m != nil && m.Errcode != nil {
		return *m.Errcode
	}
	return 0
}

func (m *Result) GetReason() string {
	if m != nil && m.Reason != nil {
		return *m.Reason
	}
	return ""
}

type EmptyRes struct {
	Result           *Result `protobuf:"bytes,1,req,name=result" json:"result,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *EmptyRes) Reset()                    { *m = EmptyRes{} }
func (m *EmptyRes) String() string            { return proto.CompactTextString(m) }
func (*EmptyRes) ProtoMessage()               {}
func (*EmptyRes) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *EmptyRes) GetResult() *Result {
	if m != nil {
		return m.Result
	}
	return nil
}

func init() {
	proto.RegisterType((*Result)(nil), "pp.Result")
	proto.RegisterType((*EmptyRes)(nil), "pp.EmptyRes")
	proto.RegisterEnum("pp.ErrCode", ErrCode_name, ErrCode_value)
}

func init() { proto.RegisterFile("pp.common.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 251 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x3c, 0x8e, 0x41, 0x4f, 0x83, 0x40,
	0x10, 0x85, 0x05, 0x63, 0xc1, 0xa1, 0x91, 0xcd, 0xaa, 0x09, 0xf1, 0x22, 0xf6, 0x60, 0x88, 0x07,
	0x0e, 0x3d, 0x7a, 0xab, 0x86, 0x1e, 0x8d, 0x69, 0x35, 0x9e, 0x11, 0x26, 0x4a, 0x04, 0x66, 0x9d,
	0x5d, 0x4c, 0xf1, 0xe7, 0xf8, 0x4b, 0xdd, 0x2d, 0x49, 0x8f, 0xf3, 0xbd, 0xcc, 0xf7, 0x1e, 0xc4,
	0x4a, 0xe5, 0x15, 0x75, 0x1d, 0xf5, 0xb9, 0x62, 0x32, 0x24, 0x7d, 0xa5, 0x16, 0xf7, 0x30, 0xdb,
	0xa0, 0x1e, 0x5a, 0x23, 0x63, 0x08, 0xf4, 0x50, 0x55, 0xa8, 0x75, 0xe2, 0xa5, 0x7e, 0x16, 0x3a,
	0x80, 0xcc, 0x15, 0xd5, 0x98, 0xf8, 0xa9, 0x97, 0x9d, 0xc8, 0x33, 0x98, 0x31, 0x96, 0x9a, 0xfa,
	0xe4, 0xd8, 0xde, 0xa7, 0x8b, 0x5b, 0x08, 0x8b, 0x4e, 0x99, 0xd1, 0x0a, 0xe4, 0x95, 0xcb, 0x9c,
	0x67, 0xff, 0x1c, 0x2d, 0x21, 0xb7, 0x6d, 0x93, 0xf9, 0xee, 0xcf, 0x83, 0xa0, 0x60, 0x7e, 0xb4,
	0x26, 0x19, 0x41, 0xb0, 0x9d, 0x5a, 0xc4, 0x91, 0x6d, 0x88, 0xde, 0x98, 0xfa, 0x8f, 0x35, 0x71,
	0x57, 0x1a, 0x01, 0x07, 0xf0, 0x3c, 0xbc, 0x7f, 0xe1, 0x28, 0x2e, 0xa4, 0x80, 0xf9, 0x1e, 0x6c,
	0xf0, 0x7b, 0x40, 0x6d, 0xc4, 0xa5, 0x23, 0xaf, 0xfd, 0x6a, 0x30, 0x9f, 0xc4, 0xcd, 0x2f, 0xd6,
	0xe2, 0x5a, 0xce, 0x21, 0x7c, 0x22, 0x53, 0xec, 0x1a, 0xa3, 0x45, 0xea, 0xf2, 0x55, 0x6b, 0x67,
	0xd6, 0xe3, 0x44, 0x6e, 0x9c, 0x74, 0x8b, 0xfc, 0x83, 0x6c, 0x37, 0x10, 0x8b, 0x4c, 0x9e, 0x43,
	0xfc, 0xc0, 0x54, 0xd6, 0x55, 0xa9, 0xcd, 0xcb, 0x6e, 0x5d, 0x36, 0xad, 0x58, 0xfe, 0x07, 0x00,
	0x00, 0xff, 0xff, 0x94, 0x6d, 0x77, 0xf5, 0x1e, 0x01, 0x00, 0x00,
}
