// Code generated by protoc-gen-go.
// source: pp.deposit.proto
// DO NOT EDIT!

package pp

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type GetDepositAddrReq struct {
	AccountId        *string `protobuf:"bytes,1,opt,name=account_id" json:"account_id,omitempty"`
	CoinType         *string `protobuf:"bytes,2,opt,name=coin_type" json:"coin_type,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *GetDepositAddrReq) Reset()                    { *m = GetDepositAddrReq{} }
func (m *GetDepositAddrReq) String() string            { return proto.CompactTextString(m) }
func (*GetDepositAddrReq) ProtoMessage()               {}
func (*GetDepositAddrReq) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{0} }

func (m *GetDepositAddrReq) GetAccountId() string {
	if m != nil && m.AccountId != nil {
		return *m.AccountId
	}
	return ""
}

func (m *GetDepositAddrReq) GetCoinType() string {
	if m != nil && m.CoinType != nil {
		return *m.CoinType
	}
	return ""
}

type GetDepositAddrRes struct {
	Result           *Result `protobuf:"bytes,1,req,name=result" json:"result,omitempty"`
	AccountId        *string `protobuf:"bytes,10,opt,name=account_id" json:"account_id,omitempty"`
	CoinType         *string `protobuf:"bytes,11,opt,name=coin_type" json:"coin_type,omitempty"`
	Address          *string `protobuf:"bytes,12,opt,name=address" json:"address,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *GetDepositAddrRes) Reset()                    { *m = GetDepositAddrRes{} }
func (m *GetDepositAddrRes) String() string            { return proto.CompactTextString(m) }
func (*GetDepositAddrRes) ProtoMessage()               {}
func (*GetDepositAddrRes) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{1} }

func (m *GetDepositAddrRes) GetResult() *Result {
	if m != nil {
		return m.Result
	}
	return nil
}

func (m *GetDepositAddrRes) GetAccountId() string {
	if m != nil && m.AccountId != nil {
		return *m.AccountId
	}
	return ""
}

func (m *GetDepositAddrRes) GetCoinType() string {
	if m != nil && m.CoinType != nil {
		return *m.CoinType
	}
	return ""
}

func (m *GetDepositAddrRes) GetAddress() string {
	if m != nil && m.Address != nil {
		return *m.Address
	}
	return ""
}

func init() {
	proto.RegisterType((*GetDepositAddrReq)(nil), "pp.GetDepositAddrReq")
	proto.RegisterType((*GetDepositAddrRes)(nil), "pp.GetDepositAddrRes")
}

func init() { proto.RegisterFile("pp.deposit.proto", fileDescriptor3) }

var fileDescriptor3 = []byte{
	// 161 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x64, 0xcd, 0xb1, 0x0a, 0x83, 0x30,
	0x10, 0xc6, 0x71, 0x74, 0x68, 0xf1, 0x2c, 0x58, 0x33, 0x89, 0x53, 0x71, 0x72, 0x72, 0xe8, 0xd8,
	0xad, 0x50, 0xe8, 0xee, 0x0b, 0x88, 0x24, 0x47, 0x09, 0xd4, 0xdc, 0x35, 0x39, 0x87, 0xbe, 0x7d,
	0xa3, 0x6e, 0x75, 0xfd, 0x71, 0xdf, 0xff, 0xe0, 0xcc, 0xdc, 0x19, 0x64, 0x0a, 0x56, 0x3a, 0xf6,
	0x24, 0xa4, 0x52, 0xe6, 0xba, 0x88, 0xaa, 0x69, 0x9a, 0xc8, 0x6d, 0xd8, 0xdc, 0xa0, 0x7c, 0xa2,
	0x3c, 0xb6, 0xc3, 0xbb, 0x31, 0xbe, 0xc7, 0x8f, 0x52, 0x00, 0xa3, 0xd6, 0x34, 0x3b, 0x19, 0xac,
	0xa9, 0x92, 0x4b, 0xd2, 0x66, 0xaa, 0x84, 0x4c, 0x93, 0x75, 0x83, 0x7c, 0x19, 0xab, 0x74, 0xa1,
	0xe6, 0xb5, 0xdf, 0x06, 0x55, 0xc3, 0xc1, 0x63, 0x98, 0xdf, 0x12, 0x77, 0x69, 0x9b, 0x5f, 0xa1,
	0x8b, 0x2f, 0xfb, 0x55, 0xfe, 0xba, 0xb0, 0xef, 0xe6, 0x2b, 0x15, 0x70, 0x1c, 0x63, 0x0d, 0x43,
	0xa8, 0x4e, 0x0b, 0xfc, 0x02, 0x00, 0x00, 0xff, 0xff, 0x6c, 0xa1, 0x36, 0x79, 0xcc, 0x00, 0x00,
	0x00,
}
