// Code generated by protoc-gen-go.
// source: pp.order.proto
// DO NOT EDIT!

package pp

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type OrderReq struct {
	AccountId        *string `protobuf:"bytes,10,opt,name=account_id" json:"account_id,omitempty"`
	CoinPair         *string `protobuf:"bytes,11,opt,name=coin_pair" json:"coin_pair,omitempty"`
	Type             *string `protobuf:"bytes,12,opt,name=type" json:"type,omitempty"`
	Amount           *uint64 `protobuf:"varint,13,opt,name=amount" json:"amount,omitempty"`
	Price            *uint64 `protobuf:"varint,14,opt,name=price" json:"price,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *OrderReq) Reset()                    { *m = OrderReq{} }
func (m *OrderReq) String() string            { return proto.CompactTextString(m) }
func (*OrderReq) ProtoMessage()               {}
func (*OrderReq) Descriptor() ([]byte, []int) { return fileDescriptor6, []int{0} }

func (m *OrderReq) GetAccountId() string {
	if m != nil && m.AccountId != nil {
		return *m.AccountId
	}
	return ""
}

func (m *OrderReq) GetCoinPair() string {
	if m != nil && m.CoinPair != nil {
		return *m.CoinPair
	}
	return ""
}

func (m *OrderReq) GetType() string {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return ""
}

func (m *OrderReq) GetAmount() uint64 {
	if m != nil && m.Amount != nil {
		return *m.Amount
	}
	return 0
}

func (m *OrderReq) GetPrice() uint64 {
	if m != nil && m.Price != nil {
		return *m.Price
	}
	return 0
}

type OrderRes struct {
	Result           *Result `protobuf:"bytes,1,req,name=result" json:"result,omitempty"`
	AccountId        *string `protobuf:"bytes,10,opt,name=account_id" json:"account_id,omitempty"`
	OrderId          *uint64 `protobuf:"varint,11,opt,name=order_id" json:"order_id,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *OrderRes) Reset()                    { *m = OrderRes{} }
func (m *OrderRes) String() string            { return proto.CompactTextString(m) }
func (*OrderRes) ProtoMessage()               {}
func (*OrderRes) Descriptor() ([]byte, []int) { return fileDescriptor6, []int{1} }

func (m *OrderRes) GetResult() *Result {
	if m != nil {
		return m.Result
	}
	return nil
}

func (m *OrderRes) GetAccountId() string {
	if m != nil && m.AccountId != nil {
		return *m.AccountId
	}
	return ""
}

func (m *OrderRes) GetOrderId() uint64 {
	if m != nil && m.OrderId != nil {
		return *m.OrderId
	}
	return 0
}

type Order struct {
	Id               *uint64 `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	Type             *string `protobuf:"bytes,3,opt,name=type" json:"type,omitempty"`
	Price            *uint64 `protobuf:"varint,4,opt,name=price" json:"price,omitempty"`
	Amount           *uint64 `protobuf:"varint,5,opt,name=amount" json:"amount,omitempty"`
	RestAmt          *uint64 `protobuf:"varint,6,opt,name=rest_amt" json:"rest_amt,omitempty"`
	CreatedAt        *int64  `protobuf:"varint,7,opt,name=created_at" json:"created_at,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *Order) Reset()                    { *m = Order{} }
func (m *Order) String() string            { return proto.CompactTextString(m) }
func (*Order) ProtoMessage()               {}
func (*Order) Descriptor() ([]byte, []int) { return fileDescriptor6, []int{2} }

func (m *Order) GetId() uint64 {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return 0
}

func (m *Order) GetType() string {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return ""
}

func (m *Order) GetPrice() uint64 {
	if m != nil && m.Price != nil {
		return *m.Price
	}
	return 0
}

func (m *Order) GetAmount() uint64 {
	if m != nil && m.Amount != nil {
		return *m.Amount
	}
	return 0
}

func (m *Order) GetRestAmt() uint64 {
	if m != nil && m.RestAmt != nil {
		return *m.RestAmt
	}
	return 0
}

func (m *Order) GetCreatedAt() int64 {
	if m != nil && m.CreatedAt != nil {
		return *m.CreatedAt
	}
	return 0
}

type GetOrderReq struct {
	Router           *string `protobuf:"bytes,1,opt,name=router" json:"router,omitempty"`
	CoinPair         *string `protobuf:"bytes,10,opt,name=coin_pair" json:"coin_pair,omitempty"`
	Type             *string `protobuf:"bytes,11,opt,name=type" json:"type,omitempty"`
	Start            *int64  `protobuf:"varint,12,opt,name=start" json:"start,omitempty"`
	End              *int64  `protobuf:"varint,13,opt,name=end" json:"end,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *GetOrderReq) Reset()                    { *m = GetOrderReq{} }
func (m *GetOrderReq) String() string            { return proto.CompactTextString(m) }
func (*GetOrderReq) ProtoMessage()               {}
func (*GetOrderReq) Descriptor() ([]byte, []int) { return fileDescriptor6, []int{3} }

func (m *GetOrderReq) GetRouter() string {
	if m != nil && m.Router != nil {
		return *m.Router
	}
	return ""
}

func (m *GetOrderReq) GetCoinPair() string {
	if m != nil && m.CoinPair != nil {
		return *m.CoinPair
	}
	return ""
}

func (m *GetOrderReq) GetType() string {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return ""
}

func (m *GetOrderReq) GetStart() int64 {
	if m != nil && m.Start != nil {
		return *m.Start
	}
	return 0
}

func (m *GetOrderReq) GetEnd() int64 {
	if m != nil && m.End != nil {
		return *m.End
	}
	return 0
}

type GetOrderRes struct {
	Result           *Result  `protobuf:"bytes,1,req,name=result" json:"result,omitempty"`
	CoinPair         *string  `protobuf:"bytes,10,opt,name=coin_pair" json:"coin_pair,omitempty"`
	Type             *string  `protobuf:"bytes,11,opt,name=type" json:"type,omitempty"`
	Orders           []*Order `protobuf:"bytes,21,rep,name=orders" json:"orders,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *GetOrderRes) Reset()                    { *m = GetOrderRes{} }
func (m *GetOrderRes) String() string            { return proto.CompactTextString(m) }
func (*GetOrderRes) ProtoMessage()               {}
func (*GetOrderRes) Descriptor() ([]byte, []int) { return fileDescriptor6, []int{4} }

func (m *GetOrderRes) GetResult() *Result {
	if m != nil {
		return m.Result
	}
	return nil
}

func (m *GetOrderRes) GetCoinPair() string {
	if m != nil && m.CoinPair != nil {
		return *m.CoinPair
	}
	return ""
}

func (m *GetOrderRes) GetType() string {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return ""
}

func (m *GetOrderRes) GetOrders() []*Order {
	if m != nil {
		return m.Orders
	}
	return nil
}

func init() {
	proto.RegisterType((*OrderReq)(nil), "pp.OrderReq")
	proto.RegisterType((*OrderRes)(nil), "pp.OrderRes")
	proto.RegisterType((*Order)(nil), "pp.Order")
	proto.RegisterType((*GetOrderReq)(nil), "pp.GetOrderReq")
	proto.RegisterType((*GetOrderRes)(nil), "pp.GetOrderRes")
}

func init() { proto.RegisterFile("pp.order.proto", fileDescriptor6) }

var fileDescriptor6 = []byte{
	// 286 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x84, 0x90, 0xcf, 0x4a, 0xf4, 0x30,
	0x14, 0xc5, 0x99, 0xa6, 0xed, 0x37, 0xbd, 0x99, 0xe9, 0xa7, 0x01, 0x21, 0xce, 0xaa, 0x74, 0x35,
	0xab, 0x2e, 0x7c, 0x09, 0x37, 0x82, 0x30, 0x4b, 0x17, 0x96, 0x90, 0x46, 0x28, 0xd8, 0x26, 0xa6,
	0xb7, 0x0b, 0xdf, 0xde, 0xdb, 0x2b, 0x53, 0xff, 0x20, 0xba, 0xbc, 0x27, 0x39, 0xbf, 0x73, 0x38,
	0x50, 0x86, 0xd0, 0xf8, 0xd8, 0xb9, 0xd8, 0x84, 0xe8, 0xd1, 0xab, 0x24, 0x84, 0xc3, 0x7f, 0xd2,
	0xac, 0x1f, 0x06, 0x3f, 0xbe, 0x8b, 0xf5, 0x23, 0x6c, 0xef, 0x97, 0x3f, 0x27, 0xf7, 0xa2, 0x14,
	0x80, 0xb1, 0xd6, 0xcf, 0x23, 0xb6, 0x7d, 0xa7, 0xa1, 0xda, 0x1c, 0x0b, 0x75, 0x09, 0x85, 0xf5,
	0xfd, 0xd8, 0x06, 0xd3, 0x47, 0x2d, 0x59, 0xda, 0x41, 0x8a, 0xaf, 0xc1, 0xe9, 0x1d, 0x5f, 0x25,
	0xe4, 0x66, 0x58, 0x3c, 0x7a, 0x4f, 0x77, 0xaa, 0xf6, 0x90, 0x85, 0xd8, 0x5b, 0xa7, 0xcb, 0xe5,
	0xac, 0xef, 0x56, 0xfe, 0xa4, 0x0e, 0x90, 0x47, 0x37, 0xcd, 0xcf, 0xa8, 0x37, 0x55, 0x72, 0x94,
	0x37, 0xd0, 0x50, 0x9b, 0x13, 0x2b, 0x3f, 0x66, 0x5f, 0xc0, 0x96, 0xfb, 0x2f, 0x8a, 0x64, 0xda,
	0x13, 0x64, 0x4c, 0xa3, 0xdf, 0x09, 0x89, 0x1b, 0x4e, 0x3c, 0xf7, 0x11, 0x6c, 0x5a, 0xf3, 0x53,
	0x7e, 0xfc, 0xa8, 0x97, 0xf1, 0x4d, 0x4c, 0xea, 0x80, 0xad, 0x19, 0x50, 0xe7, 0xac, 0x10, 0xcb,
	0x46, 0x67, 0xd0, 0x75, 0xad, 0x41, 0xfd, 0x8f, 0x34, 0x51, 0x3f, 0x80, 0xbc, 0x75, 0xb8, 0x0e,
	0x43, 0x90, 0xe8, 0x67, 0x74, 0x91, 0x13, 0xbf, 0x8d, 0x02, 0x5f, 0x46, 0x91, 0xe7, 0x12, 0x13,
	0x9a, 0x88, 0xbc, 0x91, 0x50, 0x12, 0x84, 0x1b, 0x3b, 0x1e, 0x48, 0xd4, 0xee, 0x33, 0xfb, 0xf7,
	0x51, 0xfe, 0xcc, 0xb9, 0x86, 0x9c, 0x17, 0x9a, 0xf4, 0x55, 0x25, 0xc8, 0x5c, 0x2c, 0x66, 0x46,
	0xbf, 0x05, 0x00, 0x00, 0xff, 0xff, 0x39, 0xf9, 0x5b, 0x7f, 0xfe, 0x01, 0x00, 0x00,
}
