// Code generated by protoc-gen-go.
// source: pp.order.proto
// DO NOT EDIT!

package pp

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type OrderReq struct {
	AccountId        *string `protobuf:"bytes,1,opt,name=account_id" json:"account_id,omitempty"`
	CoinPair         *string `protobuf:"bytes,10,opt,name=coin_pair" json:"coin_pair,omitempty"`
	Amount           *uint64 `protobuf:"varint,11,opt,name=amount" json:"amount,omitempty"`
	Price            *uint64 `protobuf:"varint,12,opt,name=price" json:"price,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *OrderReq) Reset()                    { *m = OrderReq{} }
func (m *OrderReq) String() string            { return proto.CompactTextString(m) }
func (*OrderReq) ProtoMessage()               {}
func (*OrderReq) Descriptor() ([]byte, []int) { return fileDescriptor6, []int{0} }

func (m *OrderReq) GetAccountId() string {
	if m != nil && m.AccountId != nil {
		return *m.AccountId
	}
	return ""
}

func (m *OrderReq) GetCoinPair() string {
	if m != nil && m.CoinPair != nil {
		return *m.CoinPair
	}
	return ""
}

func (m *OrderReq) GetAmount() uint64 {
	if m != nil && m.Amount != nil {
		return *m.Amount
	}
	return 0
}

func (m *OrderReq) GetPrice() uint64 {
	if m != nil && m.Price != nil {
		return *m.Price
	}
	return 0
}

type OrderRes struct {
	AccountId        *string `protobuf:"bytes,1,opt,name=account_id" json:"account_id,omitempty"`
	OrderId          *uint64 `protobuf:"varint,10,opt,name=order_id" json:"order_id,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *OrderRes) Reset()                    { *m = OrderRes{} }
func (m *OrderRes) String() string            { return proto.CompactTextString(m) }
func (*OrderRes) ProtoMessage()               {}
func (*OrderRes) Descriptor() ([]byte, []int) { return fileDescriptor6, []int{1} }

func (m *OrderRes) GetAccountId() string {
	if m != nil && m.AccountId != nil {
		return *m.AccountId
	}
	return ""
}

func (m *OrderRes) GetOrderId() uint64 {
	if m != nil && m.OrderId != nil {
		return *m.OrderId
	}
	return 0
}

type Order struct {
	Id               *uint64 `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	Type             *string `protobuf:"bytes,3,opt,name=type" json:"type,omitempty"`
	Price            *uint64 `protobuf:"varint,4,opt,name=price" json:"price,omitempty"`
	Amount           *uint64 `protobuf:"varint,5,opt,name=amount" json:"amount,omitempty"`
	RestAmt          *uint64 `protobuf:"varint,6,opt,name=rest_amt" json:"rest_amt,omitempty"`
	CreatedAt        *int64  `protobuf:"varint,7,opt,name=created_at" json:"created_at,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *Order) Reset()                    { *m = Order{} }
func (m *Order) String() string            { return proto.CompactTextString(m) }
func (*Order) ProtoMessage()               {}
func (*Order) Descriptor() ([]byte, []int) { return fileDescriptor6, []int{2} }

func (m *Order) GetId() uint64 {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return 0
}

func (m *Order) GetType() string {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return ""
}

func (m *Order) GetPrice() uint64 {
	if m != nil && m.Price != nil {
		return *m.Price
	}
	return 0
}

func (m *Order) GetAmount() uint64 {
	if m != nil && m.Amount != nil {
		return *m.Amount
	}
	return 0
}

func (m *Order) GetRestAmt() uint64 {
	if m != nil && m.RestAmt != nil {
		return *m.RestAmt
	}
	return 0
}

func (m *Order) GetCreatedAt() int64 {
	if m != nil && m.CreatedAt != nil {
		return *m.CreatedAt
	}
	return 0
}

type GetOrderReq struct {
	CoinPair         *string `protobuf:"bytes,1,opt,name=coin_pair" json:"coin_pair,omitempty"`
	Type             *string `protobuf:"bytes,2,opt,name=type" json:"type,omitempty"`
	Start            *int64  `protobuf:"varint,3,opt,name=start" json:"start,omitempty"`
	End              *int64  `protobuf:"varint,4,opt,name=end" json:"end,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *GetOrderReq) Reset()                    { *m = GetOrderReq{} }
func (m *GetOrderReq) String() string            { return proto.CompactTextString(m) }
func (*GetOrderReq) ProtoMessage()               {}
func (*GetOrderReq) Descriptor() ([]byte, []int) { return fileDescriptor6, []int{3} }

func (m *GetOrderReq) GetCoinPair() string {
	if m != nil && m.CoinPair != nil {
		return *m.CoinPair
	}
	return ""
}

func (m *GetOrderReq) GetType() string {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return ""
}

func (m *GetOrderReq) GetStart() int64 {
	if m != nil && m.Start != nil {
		return *m.Start
	}
	return 0
}

func (m *GetOrderReq) GetEnd() int64 {
	if m != nil && m.End != nil {
		return *m.End
	}
	return 0
}

type GetOrderRes struct {
	Result           *Result  `protobuf:"bytes,1,req,name=result" json:"result,omitempty"`
	CoinPair         *string  `protobuf:"bytes,10,opt,name=coin_pair" json:"coin_pair,omitempty"`
	Type             *string  `protobuf:"bytes,11,opt,name=type" json:"type,omitempty"`
	Orders           []*Order `protobuf:"bytes,21,rep,name=orders" json:"orders,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *GetOrderRes) Reset()                    { *m = GetOrderRes{} }
func (m *GetOrderRes) String() string            { return proto.CompactTextString(m) }
func (*GetOrderRes) ProtoMessage()               {}
func (*GetOrderRes) Descriptor() ([]byte, []int) { return fileDescriptor6, []int{4} }

func (m *GetOrderRes) GetResult() *Result {
	if m != nil {
		return m.Result
	}
	return nil
}

func (m *GetOrderRes) GetCoinPair() string {
	if m != nil && m.CoinPair != nil {
		return *m.CoinPair
	}
	return ""
}

func (m *GetOrderRes) GetType() string {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return ""
}

func (m *GetOrderRes) GetOrders() []*Order {
	if m != nil {
		return m.Orders
	}
	return nil
}

func init() {
	proto.RegisterType((*OrderReq)(nil), "pp.OrderReq")
	proto.RegisterType((*OrderRes)(nil), "pp.OrderRes")
	proto.RegisterType((*Order)(nil), "pp.Order")
	proto.RegisterType((*GetOrderReq)(nil), "pp.GetOrderReq")
	proto.RegisterType((*GetOrderRes)(nil), "pp.GetOrderRes")
}

func init() { proto.RegisterFile("pp.order.proto", fileDescriptor6) }

var fileDescriptor6 = []byte{
	// 272 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x6c, 0x50, 0xcd, 0x4a, 0xc3, 0x40,
	0x10, 0xa6, 0xd9, 0x24, 0x36, 0x93, 0x5a, 0x75, 0x41, 0x58, 0x7b, 0x2a, 0x39, 0xf5, 0x14, 0xc4,
	0x97, 0x10, 0xbc, 0x28, 0x7d, 0x81, 0xb0, 0x6c, 0x46, 0x08, 0x98, 0xec, 0xba, 0x99, 0x1e, 0x7c,
	0x7b, 0x27, 0x53, 0x13, 0x15, 0x7a, 0xfc, 0xbe, 0xfd, 0xfe, 0x76, 0x60, 0x1b, 0x42, 0xed, 0x63,
	0x8b, 0xb1, 0x0e, 0xd1, 0x93, 0xd7, 0x49, 0x08, 0xbb, 0x1b, 0xe6, 0x9c, 0xef, 0x7b, 0x3f, 0x9c,
	0xc9, 0xea, 0x0d, 0xd6, 0xaf, 0x93, 0xe6, 0x88, 0x9f, 0x5a, 0x03, 0x58, 0xe7, 0xfc, 0x69, 0xa0,
	0xa6, 0x6b, 0xcd, 0x6a, 0xbf, 0x3a, 0x14, 0xfa, 0x0e, 0x0a, 0xe7, 0xbb, 0xa1, 0x09, 0xb6, 0x8b,
	0x06, 0x84, 0xda, 0x42, 0x6e, 0xfb, 0x49, 0x65, 0x4a, 0xc6, 0xa9, 0xbe, 0x86, 0x2c, 0xc4, 0xce,
	0xa1, 0xd9, 0x4c, 0xb0, 0x7a, 0x5c, 0x12, 0xc7, 0x8b, 0x89, 0xb7, 0xb0, 0x96, 0x55, 0x13, 0x03,
	0xe2, 0x78, 0x87, 0x4c, 0x1c, 0xac, 0x4e, 0x7e, 0x64, 0xa9, 0xde, 0x40, 0x4a, 0x5f, 0x01, 0x8d,
	0x12, 0xd3, 0xd2, 0x91, 0xca, 0xe3, 0xef, 0x84, 0x4c, 0x30, 0x67, 0x46, 0x1c, 0xa9, 0xb1, 0x3d,
	0x99, 0x5c, 0x18, 0xce, 0x72, 0x11, 0x2d, 0x61, 0xdb, 0x58, 0x32, 0x57, 0xcc, 0xa9, 0xea, 0x05,
	0xca, 0x67, 0xa4, 0xe5, 0xbb, 0xff, 0xbe, 0x76, 0xde, 0x36, 0x97, 0x26, 0x73, 0xe9, 0x48, 0x36,
	0x92, 0x6c, 0x50, 0xba, 0x04, 0x85, 0x43, 0x2b, 0x0b, 0x54, 0x85, 0x7f, 0xb3, 0x46, 0xbd, 0x83,
	0x9c, 0x07, 0x9c, 0x3e, 0x88, 0x83, 0x92, 0x43, 0xf9, 0x04, 0x35, 0x1f, 0xfa, 0x28, 0xcc, 0xa5,
	0x13, 0xce, 0x3d, 0xa5, 0xa0, 0x07, 0xc8, 0xe5, 0x22, 0xa3, 0xb9, 0xdf, 0x2b, 0x36, 0x17, 0x93,
	0x59, 0xa2, 0xbf, 0x03, 0x00, 0x00, 0xff, 0xff, 0xcf, 0x42, 0xb4, 0x73, 0xc4, 0x01, 0x00, 0x00,
}
