// Code generated by protoc-gen-go.
// source: pp.output.proto
// DO NOT EDIT!

package pp

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type GetOutputReq struct {
	Hash             *string `protobuf:"bytes,1,opt,name=hash" json:"hash,omitempty"`
	CoinType         *string `protobuf:"bytes,2,opt,name=coin_type" json:"coin_type,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *GetOutputReq) Reset()                    { *m = GetOutputReq{} }
func (m *GetOutputReq) String() string            { return proto.CompactTextString(m) }
func (*GetOutputReq) ProtoMessage()               {}
func (*GetOutputReq) Descriptor() ([]byte, []int) { return fileDescriptor12, []int{0} }

func (m *GetOutputReq) GetHash() string {
	if m != nil && m.Hash != nil {
		return *m.Hash
	}
	return ""
}

func (m *GetOutputReq) GetCoinType() string {
	if m != nil && m.CoinType != nil {
		return *m.CoinType
	}
	return ""
}

type GetOutputRes struct {
	Result           *Result `protobuf:"bytes,1,opt,name=result" json:"result,omitempty"`
	Output           *Output `protobuf:"bytes,10,opt,name=output" json:"output,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *GetOutputRes) Reset()                    { *m = GetOutputRes{} }
func (m *GetOutputRes) String() string            { return proto.CompactTextString(m) }
func (*GetOutputRes) ProtoMessage()               {}
func (*GetOutputRes) Descriptor() ([]byte, []int) { return fileDescriptor12, []int{1} }

func (m *GetOutputRes) GetResult() *Result {
	if m != nil {
		return m.Result
	}
	return nil
}

func (m *GetOutputRes) GetOutput() *Output {
	if m != nil {
		return m.Output
	}
	return nil
}

type Output struct {
	Time             *uint64 `protobuf:"varint,1,opt,name=time" json:"time,omitempty"`
	SrcBlockSeq      *uint64 `protobuf:"varint,2,opt,name=src_block_seq" json:"src_block_seq,omitempty"`
	SrcTx            *string `protobuf:"bytes,3,opt,name=src_tx" json:"src_tx,omitempty"`
	OwnerAddress     *string `protobuf:"bytes,4,opt,name=owner_address" json:"owner_address,omitempty"`
	Coins            *uint64 `protobuf:"varint,5,opt,name=coins" json:"coins,omitempty"`
	Hours            *uint64 `protobuf:"varint,6,opt,name=hours" json:"hours,omitempty"`
	SpentBlockSeq    *uint64 `protobuf:"varint,7,opt,name=spent_block_seq" json:"spent_block_seq,omitempty"`
	SpentTx          *string `protobuf:"bytes,8,opt,name=spent_tx" json:"spent_tx,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *Output) Reset()                    { *m = Output{} }
func (m *Output) String() string            { return proto.CompactTextString(m) }
func (*Output) ProtoMessage()               {}
func (*Output) Descriptor() ([]byte, []int) { return fileDescriptor12, []int{2} }

func (m *Output) GetTime() uint64 {
	if m != nil && m.Time != nil {
		return *m.Time
	}
	return 0
}

func (m *Output) GetSrcBlockSeq() uint64 {
	if m != nil && m.SrcBlockSeq != nil {
		return *m.SrcBlockSeq
	}
	return 0
}

func (m *Output) GetSrcTx() string {
	if m != nil && m.SrcTx != nil {
		return *m.SrcTx
	}
	return ""
}

func (m *Output) GetOwnerAddress() string {
	if m != nil && m.OwnerAddress != nil {
		return *m.OwnerAddress
	}
	return ""
}

func (m *Output) GetCoins() uint64 {
	if m != nil && m.Coins != nil {
		return *m.Coins
	}
	return 0
}

func (m *Output) GetHours() uint64 {
	if m != nil && m.Hours != nil {
		return *m.Hours
	}
	return 0
}

func (m *Output) GetSpentBlockSeq() uint64 {
	if m != nil && m.SpentBlockSeq != nil {
		return *m.SpentBlockSeq
	}
	return 0
}

func (m *Output) GetSpentTx() string {
	if m != nil && m.SpentTx != nil {
		return *m.SpentTx
	}
	return ""
}

func init() {
	proto.RegisterType((*GetOutputReq)(nil), "pp.GetOutputReq")
	proto.RegisterType((*GetOutputRes)(nil), "pp.GetOutputRes")
	proto.RegisterType((*Output)(nil), "pp.Output")
}

func init() { proto.RegisterFile("pp.output.proto", fileDescriptor12) }

var fileDescriptor12 = []byte{
	// 234 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x54, 0x8e, 0xcf, 0x4a, 0xc3, 0x40,
	0x10, 0xc6, 0x49, 0x4d, 0x62, 0x3b, 0x36, 0x56, 0x17, 0x8a, 0x4b, 0x4f, 0x92, 0x93, 0xa7, 0x08,
	0x3e, 0x84, 0x1e, 0x85, 0xbe, 0x40, 0xa8, 0xe9, 0x40, 0x8a, 0x4d, 0x66, 0xba, 0x33, 0xc1, 0xfa,
	0x30, 0xbe, 0xab, 0xec, 0xec, 0x41, 0x7b, 0xdb, 0xfd, 0x7d, 0xf3, 0xfd, 0x81, 0x15, 0x73, 0x43,
	0x93, 0xf2, 0xa4, 0x0d, 0x07, 0x52, 0x72, 0x33, 0xe6, 0x4d, 0x84, 0x1d, 0x0d, 0x03, 0x8d, 0x09,
	0xd6, 0xcf, 0xb0, 0x7c, 0x43, 0x7d, 0xb7, 0xbb, 0x2d, 0x9e, 0xdc, 0x12, 0xf2, 0x7e, 0x27, 0xbd,
	0xcf, 0x1e, 0xb3, 0xa7, 0x85, 0xbb, 0x87, 0x45, 0x47, 0x87, 0xb1, 0xd5, 0x6f, 0x46, 0x3f, 0x8b,
	0xa8, 0x7e, 0xbd, 0x30, 0x88, 0xdb, 0x40, 0x19, 0x50, 0xa6, 0xa3, 0x9a, 0xe5, 0xe6, 0x05, 0x1a,
	0xe6, 0x66, 0x6b, 0x24, 0x6a, 0x69, 0x81, 0x87, 0x3f, 0x2d, 0x59, 0xeb, 0x9f, 0x0c, 0xca, 0xf4,
	0x8c, 0x9d, 0x7a, 0x18, 0xd0, 0x02, 0x72, 0xb7, 0x86, 0x4a, 0x42, 0xd7, 0x7e, 0x1c, 0xa9, 0xfb,
	0x6c, 0x05, 0x4f, 0xd6, 0x9b, 0xbb, 0x5b, 0x28, 0x23, 0xd6, 0xb3, 0xbf, 0xb2, 0x69, 0x6b, 0xa8,
	0xe8, 0x6b, 0xc4, 0xd0, 0xee, 0xf6, 0xfb, 0x80, 0x22, 0x3e, 0x37, 0x5c, 0x41, 0x11, 0x17, 0x8b,
	0x2f, 0xcc, 0x55, 0x41, 0xd1, 0xd3, 0x14, 0xc4, 0x97, 0xf6, 0x7d, 0x80, 0x95, 0x30, 0x8e, 0xfa,
	0x2f, 0xfd, 0xda, 0x84, 0x3b, 0x98, 0x27, 0x41, 0xcf, 0x7e, 0x1e, 0x83, 0x7e, 0x03, 0x00, 0x00,
	0xff, 0xff, 0x82, 0x85, 0xfd, 0xc8, 0x3f, 0x01, 0x00, 0x00,
}
