// Code generated by protoc-gen-go.
// source: pp.order.proto
// DO NOT EDIT!

package pp

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type OrderReq struct {
	AccountId        *string `protobuf:"bytes,1,opt,name=account_id" json:"account_id,omitempty"`
	CoinPair         *string `protobuf:"bytes,10,opt,name=coin_pair" json:"coin_pair,omitempty"`
	Amount           *uint64 `protobuf:"varint,11,opt,name=amount" json:"amount,omitempty"`
	Price            *uint64 `protobuf:"varint,12,opt,name=price" json:"price,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *OrderReq) Reset()                    { *m = OrderReq{} }
func (m *OrderReq) String() string            { return proto.CompactTextString(m) }
func (*OrderReq) ProtoMessage()               {}
func (*OrderReq) Descriptor() ([]byte, []int) { return fileDescriptor6, []int{0} }

func (m *OrderReq) GetAccountId() string {
	if m != nil && m.AccountId != nil {
		return *m.AccountId
	}
	return ""
}

func (m *OrderReq) GetCoinPair() string {
	if m != nil && m.CoinPair != nil {
		return *m.CoinPair
	}
	return ""
}

func (m *OrderReq) GetAmount() uint64 {
	if m != nil && m.Amount != nil {
		return *m.Amount
	}
	return 0
}

func (m *OrderReq) GetPrice() uint64 {
	if m != nil && m.Price != nil {
		return *m.Price
	}
	return 0
}

type OrderRes struct {
	Result           *Result `protobuf:"bytes,1,req,name=result" json:"result,omitempty"`
	AccountId        *string `protobuf:"bytes,10,opt,name=account_id" json:"account_id,omitempty"`
	OrderId          *uint64 `protobuf:"varint,11,opt,name=order_id" json:"order_id,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *OrderRes) Reset()                    { *m = OrderRes{} }
func (m *OrderRes) String() string            { return proto.CompactTextString(m) }
func (*OrderRes) ProtoMessage()               {}
func (*OrderRes) Descriptor() ([]byte, []int) { return fileDescriptor6, []int{1} }

func (m *OrderRes) GetResult() *Result {
	if m != nil {
		return m.Result
	}
	return nil
}

func (m *OrderRes) GetAccountId() string {
	if m != nil && m.AccountId != nil {
		return *m.AccountId
	}
	return ""
}

func (m *OrderRes) GetOrderId() uint64 {
	if m != nil && m.OrderId != nil {
		return *m.OrderId
	}
	return 0
}

type Order struct {
	Id               *uint64 `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	Type             *string `protobuf:"bytes,3,opt,name=type" json:"type,omitempty"`
	Price            *uint64 `protobuf:"varint,4,opt,name=price" json:"price,omitempty"`
	Amount           *uint64 `protobuf:"varint,5,opt,name=amount" json:"amount,omitempty"`
	RestAmt          *uint64 `protobuf:"varint,6,opt,name=rest_amt" json:"rest_amt,omitempty"`
	CreatedAt        *int64  `protobuf:"varint,7,opt,name=created_at" json:"created_at,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *Order) Reset()                    { *m = Order{} }
func (m *Order) String() string            { return proto.CompactTextString(m) }
func (*Order) ProtoMessage()               {}
func (*Order) Descriptor() ([]byte, []int) { return fileDescriptor6, []int{2} }

func (m *Order) GetId() uint64 {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return 0
}

func (m *Order) GetType() string {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return ""
}

func (m *Order) GetPrice() uint64 {
	if m != nil && m.Price != nil {
		return *m.Price
	}
	return 0
}

func (m *Order) GetAmount() uint64 {
	if m != nil && m.Amount != nil {
		return *m.Amount
	}
	return 0
}

func (m *Order) GetRestAmt() uint64 {
	if m != nil && m.RestAmt != nil {
		return *m.RestAmt
	}
	return 0
}

func (m *Order) GetCreatedAt() int64 {
	if m != nil && m.CreatedAt != nil {
		return *m.CreatedAt
	}
	return 0
}

type GetOrderReq struct {
	CoinPair         *string `protobuf:"bytes,10,opt,name=coin_pair" json:"coin_pair,omitempty"`
	Start            *int64  `protobuf:"varint,11,opt,name=start" json:"start,omitempty"`
	End              *int64  `protobuf:"varint,12,opt,name=end" json:"end,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *GetOrderReq) Reset()                    { *m = GetOrderReq{} }
func (m *GetOrderReq) String() string            { return proto.CompactTextString(m) }
func (*GetOrderReq) ProtoMessage()               {}
func (*GetOrderReq) Descriptor() ([]byte, []int) { return fileDescriptor6, []int{3} }

func (m *GetOrderReq) GetCoinPair() string {
	if m != nil && m.CoinPair != nil {
		return *m.CoinPair
	}
	return ""
}

func (m *GetOrderReq) GetStart() int64 {
	if m != nil && m.Start != nil {
		return *m.Start
	}
	return 0
}

func (m *GetOrderReq) GetEnd() int64 {
	if m != nil && m.End != nil {
		return *m.End
	}
	return 0
}

type GetOrderRes struct {
	Result           *Result  `protobuf:"bytes,1,req,name=result" json:"result,omitempty"`
	CoinPair         *string  `protobuf:"bytes,10,opt,name=coin_pair" json:"coin_pair,omitempty"`
	Type             *string  `protobuf:"bytes,11,opt,name=type" json:"type,omitempty"`
	Orders           []*Order `protobuf:"bytes,21,rep,name=orders" json:"orders,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *GetOrderRes) Reset()                    { *m = GetOrderRes{} }
func (m *GetOrderRes) String() string            { return proto.CompactTextString(m) }
func (*GetOrderRes) ProtoMessage()               {}
func (*GetOrderRes) Descriptor() ([]byte, []int) { return fileDescriptor6, []int{4} }

func (m *GetOrderRes) GetResult() *Result {
	if m != nil {
		return m.Result
	}
	return nil
}

func (m *GetOrderRes) GetCoinPair() string {
	if m != nil && m.CoinPair != nil {
		return *m.CoinPair
	}
	return ""
}

func (m *GetOrderRes) GetType() string {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return ""
}

func (m *GetOrderRes) GetOrders() []*Order {
	if m != nil {
		return m.Orders
	}
	return nil
}

func init() {
	proto.RegisterType((*OrderReq)(nil), "pp.OrderReq")
	proto.RegisterType((*OrderRes)(nil), "pp.OrderRes")
	proto.RegisterType((*Order)(nil), "pp.Order")
	proto.RegisterType((*GetOrderReq)(nil), "pp.GetOrderReq")
	proto.RegisterType((*GetOrderRes)(nil), "pp.GetOrderRes")
}

func init() { proto.RegisterFile("pp.order.proto", fileDescriptor6) }

var fileDescriptor6 = []byte{
	// 274 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x7c, 0x90, 0x31, 0x4f, 0xc3, 0x30,
	0x10, 0x85, 0xd5, 0x38, 0x09, 0xcd, 0xa5, 0x14, 0xb0, 0x84, 0x64, 0x3a, 0x55, 0x99, 0x3a, 0x65,
	0x60, 0x66, 0x67, 0x41, 0x02, 0xf5, 0x0f, 0x44, 0x96, 0x73, 0x48, 0x91, 0x48, 0x6c, 0x9c, 0xeb,
	0xc0, 0xbf, 0xe7, 0x72, 0x81, 0x80, 0x50, 0xc5, 0x78, 0xcf, 0x77, 0xdf, 0x7b, 0xcf, 0xb0, 0x0d,
	0xa1, 0xf6, 0xb1, 0xc5, 0x58, 0x87, 0xe8, 0xc9, 0xeb, 0x24, 0x84, 0xdd, 0x15, 0x6b, 0xce, 0xf7,
	0xbd, 0x1f, 0x66, 0xb1, 0x7a, 0x81, 0xf5, 0xf3, 0xb4, 0x73, 0xc4, 0x77, 0xad, 0x01, 0xac, 0x73,
	0xfe, 0x34, 0x50, 0xd3, 0xb5, 0x66, 0xb5, 0x5f, 0x1d, 0x0a, 0x7d, 0x03, 0x85, 0xf3, 0xdd, 0xd0,
	0x04, 0xdb, 0x45, 0x03, 0x22, 0x6d, 0x21, 0xb7, 0xfd, 0xb4, 0x65, 0x4a, 0x9e, 0x53, 0x7d, 0x09,
	0x59, 0x88, 0x9d, 0x43, 0xb3, 0x99, 0xc6, 0xea, 0x69, 0x21, 0x8e, 0x7a, 0x07, 0x79, 0xc4, 0xf1,
	0xf4, 0x46, 0x4c, 0x4b, 0x0e, 0xe5, 0x3d, 0xd4, 0xec, 0x7f, 0x14, 0xe5, 0x8f, 0xdb, 0x8c, 0xbe,
	0x86, 0xb5, 0x24, 0x9e, 0x14, 0x81, 0x57, 0xaf, 0x90, 0x09, 0x8d, 0xb7, 0x93, 0xaf, 0x50, 0xa9,
	0xde, 0x40, 0x4a, 0x1f, 0x01, 0x8d, 0x92, 0xa3, 0xc5, 0x3f, 0x95, 0xc7, 0x9f, 0x78, 0x99, 0xcc,
	0xcc, 0xe4, 0x0c, 0xd4, 0xd8, 0x9e, 0x4c, 0x2e, 0x0a, 0xb3, 0x5c, 0x44, 0x4b, 0xd8, 0x36, 0x96,
	0xcc, 0x05, 0x6b, 0xaa, 0x7a, 0x80, 0xf2, 0x11, 0x69, 0xf9, 0x8a, 0x33, 0xb5, 0xd9, 0x66, 0x24,
	0x1b, 0xe7, 0xd6, 0x4a, 0x97, 0xa0, 0x70, 0x68, 0xa5, 0xb3, 0xaa, 0xf0, 0xf7, 0xf5, 0xff, 0xb5,
	0xcf, 0x90, 0xbf, 0xeb, 0x94, 0x32, 0xdd, 0x41, 0x2e, 0x7f, 0x30, 0x9a, 0xdb, 0xbd, 0xe2, 0xe3,
	0x62, 0x3a, 0x16, 0xf4, 0x67, 0x00, 0x00, 0x00, 0xff, 0xff, 0x40, 0x66, 0x79, 0xfb, 0xd2, 0x01,
	0x00, 0x00,
}
