// Code generated by protoc-gen-go.
// source: pp.request.proto
// DO NOT EDIT!

package pp

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type Request struct {
	Path             *string `protobuf:"bytes,1,req,name=path" json:"path,omitempty"`
	Data             []byte  `protobuf:"bytes,10,opt,name=data" json:"data,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *Request) Reset()                    { *m = Request{} }
func (m *Request) String() string            { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()               {}
func (*Request) Descriptor() ([]byte, []int) { return fileDescriptor8, []int{0} }

func (m *Request) GetPath() string {
	if m != nil && m.Path != nil {
		return *m.Path
	}
	return ""
}

func (m *Request) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func init() {
	proto.RegisterType((*Request)(nil), "pp.Request")
}

func init() { proto.RegisterFile("pp.request.proto", fileDescriptor8) }

var fileDescriptor8 = []byte{
	// 79 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xe2, 0x12, 0x28, 0x28, 0xd0, 0x2b,
	0x4a, 0x2d, 0x2c, 0x4d, 0x2d, 0x2e, 0xd1, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x2a, 0x28,
	0x50, 0x52, 0xe5, 0x62, 0x0f, 0x82, 0x08, 0x0a, 0xf1, 0x70, 0xb1, 0x14, 0x24, 0x96, 0x64, 0x48,
	0x30, 0x2a, 0x30, 0x69, 0x70, 0x82, 0x78, 0x29, 0x89, 0x25, 0x89, 0x12, 0x5c, 0x0a, 0x8c, 0x1a,
	0x3c, 0x80, 0x00, 0x00, 0x00, 0xff, 0xff, 0x78, 0xe2, 0x56, 0xf9, 0x3d, 0x00, 0x00, 0x00,
}
