// Code generated by protoc-gen-go.
// source: pp.transaction.proto
// DO NOT EDIT!

package pp

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type InjectTxnReq struct {
	CoinType         *string `protobuf:"bytes,10,opt,name=coin_type" json:"coin_type,omitempty"`
	Tx               *string `protobuf:"bytes,20,opt,name=tx" json:"tx,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *InjectTxnReq) Reset()                    { *m = InjectTxnReq{} }
func (m *InjectTxnReq) String() string            { return proto.CompactTextString(m) }
func (*InjectTxnReq) ProtoMessage()               {}
func (*InjectTxnReq) Descriptor() ([]byte, []int) { return fileDescriptor10, []int{0} }

func (m *InjectTxnReq) GetCoinType() string {
	if m != nil && m.CoinType != nil {
		return *m.CoinType
	}
	return ""
}

func (m *InjectTxnReq) GetTx() string {
	if m != nil && m.Tx != nil {
		return *m.Tx
	}
	return ""
}

type InjectTxnRes struct {
	Result           *Result `protobuf:"bytes,1,req,name=result" json:"result,omitempty"`
	Txid             *string `protobuf:"bytes,10,opt,name=txid" json:"txid,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *InjectTxnRes) Reset()                    { *m = InjectTxnRes{} }
func (m *InjectTxnRes) String() string            { return proto.CompactTextString(m) }
func (*InjectTxnRes) ProtoMessage()               {}
func (*InjectTxnRes) Descriptor() ([]byte, []int) { return fileDescriptor10, []int{1} }

func (m *InjectTxnRes) GetResult() *Result {
	if m != nil {
		return m.Result
	}
	return nil
}

func (m *InjectTxnRes) GetTxid() string {
	if m != nil && m.Txid != nil {
		return *m.Txid
	}
	return ""
}

type GetTxReq struct {
	CoinType         *string `protobuf:"bytes,10,opt,name=coin_type" json:"coin_type,omitempty"`
	Txid             *string `protobuf:"bytes,20,opt,name=txid" json:"txid,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *GetTxReq) Reset()                    { *m = GetTxReq{} }
func (m *GetTxReq) String() string            { return proto.CompactTextString(m) }
func (*GetTxReq) ProtoMessage()               {}
func (*GetTxReq) Descriptor() ([]byte, []int) { return fileDescriptor10, []int{2} }

func (m *GetTxReq) GetCoinType() string {
	if m != nil && m.CoinType != nil {
		return *m.CoinType
	}
	return ""
}

func (m *GetTxReq) GetTxid() string {
	if m != nil && m.Txid != nil {
		return *m.Txid
	}
	return ""
}

type Tx struct {
	Btc              *BtcTx `protobuf:"bytes,10,opt,name=btc" json:"btc,omitempty"`
	Sky              *SkyTx `protobuf:"bytes,20,opt,name=sky" json:"sky,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *Tx) Reset()                    { *m = Tx{} }
func (m *Tx) String() string            { return proto.CompactTextString(m) }
func (*Tx) ProtoMessage()               {}
func (*Tx) Descriptor() ([]byte, []int) { return fileDescriptor10, []int{3} }

func (m *Tx) GetBtc() *BtcTx {
	if m != nil {
		return m.Btc
	}
	return nil
}

func (m *Tx) GetSky() *SkyTx {
	if m != nil {
		return m.Sky
	}
	return nil
}

type GetTxRes struct {
	Result           *Result `protobuf:"bytes,1,req,name=result" json:"result,omitempty"`
	CoinType         *string `protobuf:"bytes,10,opt,name=coin_type" json:"coin_type,omitempty"`
	Tx               *Tx     `protobuf:"bytes,20,opt,name=tx" json:"tx,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *GetTxRes) Reset()                    { *m = GetTxRes{} }
func (m *GetTxRes) String() string            { return proto.CompactTextString(m) }
func (*GetTxRes) ProtoMessage()               {}
func (*GetTxRes) Descriptor() ([]byte, []int) { return fileDescriptor10, []int{4} }

func (m *GetTxRes) GetResult() *Result {
	if m != nil {
		return m.Result
	}
	return nil
}

func (m *GetTxRes) GetCoinType() string {
	if m != nil && m.CoinType != nil {
		return *m.CoinType
	}
	return ""
}

func (m *GetTxRes) GetTx() *Tx {
	if m != nil {
		return m.Tx
	}
	return nil
}

type GetRawTxReq struct {
	CoinType         *string `protobuf:"bytes,10,opt,name=coin_type" json:"coin_type,omitempty"`
	Txid             *string `protobuf:"bytes,20,opt,name=txid" json:"txid,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *GetRawTxReq) Reset()                    { *m = GetRawTxReq{} }
func (m *GetRawTxReq) String() string            { return proto.CompactTextString(m) }
func (*GetRawTxReq) ProtoMessage()               {}
func (*GetRawTxReq) Descriptor() ([]byte, []int) { return fileDescriptor10, []int{5} }

func (m *GetRawTxReq) GetCoinType() string {
	if m != nil && m.CoinType != nil {
		return *m.CoinType
	}
	return ""
}

func (m *GetRawTxReq) GetTxid() string {
	if m != nil && m.Txid != nil {
		return *m.Txid
	}
	return ""
}

type GetRawTxRes struct {
	Result           *Result `protobuf:"bytes,1,req,name=result" json:"result,omitempty"`
	CoinType         *string `protobuf:"bytes,10,opt,name=coin_type" json:"coin_type,omitempty"`
	Rawtx            *string `protobuf:"bytes,20,opt,name=rawtx" json:"rawtx,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *GetRawTxRes) Reset()                    { *m = GetRawTxRes{} }
func (m *GetRawTxRes) String() string            { return proto.CompactTextString(m) }
func (*GetRawTxRes) ProtoMessage()               {}
func (*GetRawTxRes) Descriptor() ([]byte, []int) { return fileDescriptor10, []int{6} }

func (m *GetRawTxRes) GetResult() *Result {
	if m != nil {
		return m.Result
	}
	return nil
}

func (m *GetRawTxRes) GetCoinType() string {
	if m != nil && m.CoinType != nil {
		return *m.CoinType
	}
	return ""
}

func (m *GetRawTxRes) GetRawtx() string {
	if m != nil && m.Rawtx != nil {
		return *m.Rawtx
	}
	return ""
}

type BtcTx struct {
	Txid             *string    `protobuf:"bytes,10,opt,name=txid" json:"txid,omitempty"`
	Version          *uint32    `protobuf:"varint,11,opt,name=version" json:"version,omitempty"`
	Locktime         *uint32    `protobuf:"varint,12,opt,name=locktime" json:"locktime,omitempty"`
	Vin              []*BtcVin  `protobuf:"bytes,13,rep,name=vin" json:"vin,omitempty"`
	Vout             []*BtcVout `protobuf:"bytes,14,rep,name=vout" json:"vout,omitempty"`
	Blockhash        *string    `protobuf:"bytes,15,opt,name=blockhash" json:"blockhash,omitempty"`
	Confirmations    *uint64    `protobuf:"varint,16,opt,name=confirmations" json:"confirmations,omitempty"`
	Time             *int64     `protobuf:"varint,17,opt,name=time" json:"time,omitempty"`
	Blocktime        *int64     `protobuf:"varint,18,opt,name=blocktime" json:"blocktime,omitempty"`
	XXX_unrecognized []byte     `json:"-"`
}

func (m *BtcTx) Reset()                    { *m = BtcTx{} }
func (m *BtcTx) String() string            { return proto.CompactTextString(m) }
func (*BtcTx) ProtoMessage()               {}
func (*BtcTx) Descriptor() ([]byte, []int) { return fileDescriptor10, []int{7} }

func (m *BtcTx) GetTxid() string {
	if m != nil && m.Txid != nil {
		return *m.Txid
	}
	return ""
}

func (m *BtcTx) GetVersion() uint32 {
	if m != nil && m.Version != nil {
		return *m.Version
	}
	return 0
}

func (m *BtcTx) GetLocktime() uint32 {
	if m != nil && m.Locktime != nil {
		return *m.Locktime
	}
	return 0
}

func (m *BtcTx) GetVin() []*BtcVin {
	if m != nil {
		return m.Vin
	}
	return nil
}

func (m *BtcTx) GetVout() []*BtcVout {
	if m != nil {
		return m.Vout
	}
	return nil
}

func (m *BtcTx) GetBlockhash() string {
	if m != nil && m.Blockhash != nil {
		return *m.Blockhash
	}
	return ""
}

func (m *BtcTx) GetConfirmations() uint64 {
	if m != nil && m.Confirmations != nil {
		return *m.Confirmations
	}
	return 0
}

func (m *BtcTx) GetTime() int64 {
	if m != nil && m.Time != nil {
		return *m.Time
	}
	return 0
}

func (m *BtcTx) GetBlocktime() int64 {
	if m != nil && m.Blocktime != nil {
		return *m.Blocktime
	}
	return 0
}

type BtcVin struct {
	Coinbase         *string       `protobuf:"bytes,10,opt,name=coinbase" json:"coinbase,omitempty"`
	Txid             *string       `protobuf:"bytes,11,opt,name=txid" json:"txid,omitempty"`
	Vout             *uint32       `protobuf:"varint,12,opt,name=vout" json:"vout,omitempty"`
	ScriptSig        *BtcScriptSig `protobuf:"bytes,13,opt,name=scriptSig" json:"scriptSig,omitempty"`
	Sequence         *uint32       `protobuf:"varint,14,opt,name=sequence" json:"sequence,omitempty"`
	XXX_unrecognized []byte        `json:"-"`
}

func (m *BtcVin) Reset()                    { *m = BtcVin{} }
func (m *BtcVin) String() string            { return proto.CompactTextString(m) }
func (*BtcVin) ProtoMessage()               {}
func (*BtcVin) Descriptor() ([]byte, []int) { return fileDescriptor10, []int{8} }

func (m *BtcVin) GetCoinbase() string {
	if m != nil && m.Coinbase != nil {
		return *m.Coinbase
	}
	return ""
}

func (m *BtcVin) GetTxid() string {
	if m != nil && m.Txid != nil {
		return *m.Txid
	}
	return ""
}

func (m *BtcVin) GetVout() uint32 {
	if m != nil && m.Vout != nil {
		return *m.Vout
	}
	return 0
}

func (m *BtcVin) GetScriptSig() *BtcScriptSig {
	if m != nil {
		return m.ScriptSig
	}
	return nil
}

func (m *BtcVin) GetSequence() uint32 {
	if m != nil && m.Sequence != nil {
		return *m.Sequence
	}
	return 0
}

type BtcScriptSig struct {
	Asm              *string `protobuf:"bytes,10,opt,name=asm" json:"asm,omitempty"`
	Hex              *string `protobuf:"bytes,11,opt,name=hex" json:"hex,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *BtcScriptSig) Reset()                    { *m = BtcScriptSig{} }
func (m *BtcScriptSig) String() string            { return proto.CompactTextString(m) }
func (*BtcScriptSig) ProtoMessage()               {}
func (*BtcScriptSig) Descriptor() ([]byte, []int) { return fileDescriptor10, []int{9} }

func (m *BtcScriptSig) GetAsm() string {
	if m != nil && m.Asm != nil {
		return *m.Asm
	}
	return ""
}

func (m *BtcScriptSig) GetHex() string {
	if m != nil && m.Hex != nil {
		return *m.Hex
	}
	return ""
}

type BtcVout struct {
	Value            *string                `protobuf:"bytes,10,opt,name=value" json:"value,omitempty"`
	N                *uint32                `protobuf:"varint,11,opt,name=n" json:"n,omitempty"`
	ScriptPubkey     *BtcScriptPubKeyResult `protobuf:"bytes,12,opt,name=scriptPubkey" json:"scriptPubkey,omitempty"`
	XXX_unrecognized []byte                 `json:"-"`
}

func (m *BtcVout) Reset()                    { *m = BtcVout{} }
func (m *BtcVout) String() string            { return proto.CompactTextString(m) }
func (*BtcVout) ProtoMessage()               {}
func (*BtcVout) Descriptor() ([]byte, []int) { return fileDescriptor10, []int{10} }

func (m *BtcVout) GetValue() string {
	if m != nil && m.Value != nil {
		return *m.Value
	}
	return ""
}

func (m *BtcVout) GetN() uint32 {
	if m != nil && m.N != nil {
		return *m.N
	}
	return 0
}

func (m *BtcVout) GetScriptPubkey() *BtcScriptPubKeyResult {
	if m != nil {
		return m.ScriptPubkey
	}
	return nil
}

type BtcScriptPubKeyResult struct {
	Asm              *string  `protobuf:"bytes,10,opt,name=asm" json:"asm,omitempty"`
	Hex              *string  `protobuf:"bytes,11,opt,name=hex" json:"hex,omitempty"`
	ReqSigs          *int32   `protobuf:"varint,12,opt,name=reqSigs" json:"reqSigs,omitempty"`
	Type             *string  `protobuf:"bytes,13,opt,name=type" json:"type,omitempty"`
	Addresses        []string `protobuf:"bytes,14,rep,name=addresses" json:"addresses,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *BtcScriptPubKeyResult) Reset()                    { *m = BtcScriptPubKeyResult{} }
func (m *BtcScriptPubKeyResult) String() string            { return proto.CompactTextString(m) }
func (*BtcScriptPubKeyResult) ProtoMessage()               {}
func (*BtcScriptPubKeyResult) Descriptor() ([]byte, []int) { return fileDescriptor10, []int{11} }

func (m *BtcScriptPubKeyResult) GetAsm() string {
	if m != nil && m.Asm != nil {
		return *m.Asm
	}
	return ""
}

func (m *BtcScriptPubKeyResult) GetHex() string {
	if m != nil && m.Hex != nil {
		return *m.Hex
	}
	return ""
}

func (m *BtcScriptPubKeyResult) GetReqSigs() int32 {
	if m != nil && m.ReqSigs != nil {
		return *m.ReqSigs
	}
	return 0
}

func (m *BtcScriptPubKeyResult) GetType() string {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return ""
}

func (m *BtcScriptPubKeyResult) GetAddresses() []string {
	if m != nil {
		return m.Addresses
	}
	return nil
}

type SkyTx struct {
	Length           *uint32        `protobuf:"varint,10,opt,name=length" json:"length,omitempty"`
	Type             *int32         `protobuf:"varint,11,opt,name=type" json:"type,omitempty"`
	Hash             *string        `protobuf:"bytes,12,opt,name=hash" json:"hash,omitempty"`
	InnerHash        *string        `protobuf:"bytes,13,opt,name=inner_hash" json:"inner_hash,omitempty"`
	Sigs             []string       `protobuf:"bytes,14,rep,name=sigs" json:"sigs,omitempty"`
	Inputs           []string       `protobuf:"bytes,15,rep,name=inputs" json:"inputs,omitempty"`
	Outputs          []*SkyTxOutput `protobuf:"bytes,16,rep,name=outputs" json:"outputs,omitempty"`
	Unknow           *bool          `protobuf:"varint,18,opt,name=unknow" json:"unknow,omitempty"`
	Confirmed        *bool          `protobuf:"varint,19,opt,name=confirmed" json:"confirmed,omitempty"`
	Height           *uint64        `protobuf:"varint,20,opt,name=height" json:"height,omitempty"`
	XXX_unrecognized []byte         `json:"-"`
}

func (m *SkyTx) Reset()                    { *m = SkyTx{} }
func (m *SkyTx) String() string            { return proto.CompactTextString(m) }
func (*SkyTx) ProtoMessage()               {}
func (*SkyTx) Descriptor() ([]byte, []int) { return fileDescriptor10, []int{12} }

func (m *SkyTx) GetLength() uint32 {
	if m != nil && m.Length != nil {
		return *m.Length
	}
	return 0
}

func (m *SkyTx) GetType() int32 {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return 0
}

func (m *SkyTx) GetHash() string {
	if m != nil && m.Hash != nil {
		return *m.Hash
	}
	return ""
}

func (m *SkyTx) GetInnerHash() string {
	if m != nil && m.InnerHash != nil {
		return *m.InnerHash
	}
	return ""
}

func (m *SkyTx) GetSigs() []string {
	if m != nil {
		return m.Sigs
	}
	return nil
}

func (m *SkyTx) GetInputs() []string {
	if m != nil {
		return m.Inputs
	}
	return nil
}

func (m *SkyTx) GetOutputs() []*SkyTxOutput {
	if m != nil {
		return m.Outputs
	}
	return nil
}

func (m *SkyTx) GetUnknow() bool {
	if m != nil && m.Unknow != nil {
		return *m.Unknow
	}
	return false
}

func (m *SkyTx) GetConfirmed() bool {
	if m != nil && m.Confirmed != nil {
		return *m.Confirmed
	}
	return false
}

func (m *SkyTx) GetHeight() uint64 {
	if m != nil && m.Height != nil {
		return *m.Height
	}
	return 0
}

type SkyTxOutput struct {
	Hash             *string `protobuf:"bytes,10,opt,name=hash" json:"hash,omitempty"`
	Address          *string `protobuf:"bytes,11,opt,name=address" json:"address,omitempty"`
	Coins            *string `protobuf:"bytes,12,opt,name=coins" json:"coins,omitempty"`
	Hours            *uint64 `protobuf:"varint,13,opt,name=hours" json:"hours,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *SkyTxOutput) Reset()                    { *m = SkyTxOutput{} }
func (m *SkyTxOutput) String() string            { return proto.CompactTextString(m) }
func (*SkyTxOutput) ProtoMessage()               {}
func (*SkyTxOutput) Descriptor() ([]byte, []int) { return fileDescriptor10, []int{13} }

func (m *SkyTxOutput) GetHash() string {
	if m != nil && m.Hash != nil {
		return *m.Hash
	}
	return ""
}

func (m *SkyTxOutput) GetAddress() string {
	if m != nil && m.Address != nil {
		return *m.Address
	}
	return ""
}

func (m *SkyTxOutput) GetCoins() string {
	if m != nil && m.Coins != nil {
		return *m.Coins
	}
	return ""
}

func (m *SkyTxOutput) GetHours() uint64 {
	if m != nil && m.Hours != nil {
		return *m.Hours
	}
	return 0
}

func init() {
	proto.RegisterType((*InjectTxnReq)(nil), "pp.InjectTxnReq")
	proto.RegisterType((*InjectTxnRes)(nil), "pp.InjectTxnRes")
	proto.RegisterType((*GetTxReq)(nil), "pp.GetTxReq")
	proto.RegisterType((*Tx)(nil), "pp.Tx")
	proto.RegisterType((*GetTxRes)(nil), "pp.GetTxRes")
	proto.RegisterType((*GetRawTxReq)(nil), "pp.GetRawTxReq")
	proto.RegisterType((*GetRawTxRes)(nil), "pp.GetRawTxRes")
	proto.RegisterType((*BtcTx)(nil), "pp.BtcTx")
	proto.RegisterType((*BtcVin)(nil), "pp.BtcVin")
	proto.RegisterType((*BtcScriptSig)(nil), "pp.BtcScriptSig")
	proto.RegisterType((*BtcVout)(nil), "pp.BtcVout")
	proto.RegisterType((*BtcScriptPubKeyResult)(nil), "pp.BtcScriptPubKeyResult")
	proto.RegisterType((*SkyTx)(nil), "pp.SkyTx")
	proto.RegisterType((*SkyTxOutput)(nil), "pp.SkyTxOutput")
}

func init() { proto.RegisterFile("pp.transaction.proto", fileDescriptor10) }

var fileDescriptor10 = []byte{
	// 609 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x94, 0x53, 0x41, 0x6f, 0xda, 0x4c,
	0x10, 0x95, 0x01, 0x13, 0x3c, 0xc6, 0x40, 0xfc, 0x25, 0x5f, 0x37, 0x39, 0x59, 0xee, 0x05, 0xa9,
	0x2a, 0x95, 0x50, 0x0f, 0x3d, 0xe7, 0x12, 0xb5, 0x51, 0xd5, 0x28, 0xa0, 0x5e, 0x23, 0x63, 0xb6,
	0x78, 0x0b, 0xde, 0xdd, 0x78, 0xd7, 0xc4, 0xfc, 0xb2, 0x4a, 0xfd, 0x75, 0xd5, 0x8e, 0xbd, 0x56,
	0xa8, 0x92, 0xaa, 0xbd, 0xe1, 0xb7, 0x33, 0xef, 0xbd, 0x99, 0x79, 0xc0, 0x99, 0x94, 0x33, 0x5d,
	0x24, 0x5c, 0x25, 0xa9, 0x66, 0x82, 0xcf, 0x64, 0x21, 0xb4, 0x08, 0x3b, 0x52, 0x5e, 0x8e, 0xa5,
	0x9c, 0xa5, 0x22, 0xcf, 0x2d, 0x18, 0xbf, 0x85, 0xe1, 0x47, 0xfe, 0x9d, 0xa6, 0x7a, 0x59, 0xf1,
	0x3b, 0xfa, 0x10, 0x9e, 0x82, 0x97, 0x0a, 0xc6, 0xef, 0xf5, 0x41, 0x52, 0x02, 0x91, 0x33, 0xf5,
	0x42, 0x80, 0x8e, 0xae, 0xc8, 0x99, 0xf9, 0x1d, 0x7f, 0x38, 0x2a, 0x57, 0xe1, 0x25, 0xf4, 0x0b,
	0xaa, 0xca, 0x9d, 0x26, 0x4e, 0xd4, 0x99, 0xfa, 0x73, 0x98, 0x49, 0x39, 0xbb, 0x43, 0x24, 0x1c,
	0x42, 0x4f, 0x57, 0x6c, 0x5d, 0xb3, 0xc4, 0x6f, 0x60, 0x70, 0x4d, 0xf5, 0xb2, 0x7a, 0x41, 0xc4,
	0x16, 0xd7, 0x32, 0xef, 0xa1, 0xb3, 0xac, 0xc2, 0xff, 0xa1, 0xbb, 0xd2, 0x29, 0x16, 0xf8, 0x73,
	0xcf, 0x30, 0x5f, 0xe9, 0xb4, 0xc6, 0xd5, 0xf6, 0x80, 0xa5, 0x0d, 0xbe, 0xd8, 0x1e, 0x96, 0x55,
	0xfc, 0xb9, 0x95, 0xf8, 0xb3, 0xb1, 0x67, 0xe4, 0xc3, 0x76, 0x46, 0x7f, 0xde, 0x37, 0xa5, 0xcb,
	0x2a, 0x9e, 0x81, 0x7f, 0x4d, 0xf5, 0x5d, 0xf2, 0xf8, 0x97, 0xa6, 0x6f, 0x9e, 0xd6, 0xff, 0xb3,
	0x83, 0x00, 0xdc, 0x22, 0x79, 0x6c, 0x17, 0xfd, 0xc3, 0x01, 0xb7, 0x9e, 0xf6, 0x68, 0x8d, 0xe1,
	0x18, 0x4e, 0xf6, 0xb4, 0x50, 0x4c, 0x70, 0xe2, 0x47, 0xce, 0x34, 0x08, 0x27, 0x30, 0xd8, 0x89,
	0x74, 0xab, 0x59, 0x4e, 0xc9, 0x10, 0x91, 0x57, 0xd0, 0xdd, 0x33, 0x4e, 0x82, 0xa8, 0x6b, 0x55,
	0xaf, 0x74, 0xfa, 0x95, 0xf1, 0xf0, 0x02, 0x7a, 0x7b, 0x51, 0x6a, 0x32, 0xc2, 0x17, 0xdf, 0xbe,
	0x88, 0x12, 0x0d, 0xad, 0x0c, 0x4d, 0x96, 0xa8, 0x8c, 0x8c, 0x51, 0xe9, 0x1c, 0x82, 0x54, 0xf0,
	0x6f, 0xac, 0xc8, 0x13, 0x13, 0x22, 0x45, 0x26, 0x91, 0x33, 0xed, 0xa1, 0x1d, 0xa3, 0x75, 0x1a,
	0x39, 0xd3, 0x6e, 0xdb, 0x87, 0x50, 0x68, 0xa0, 0x38, 0x87, 0x7e, 0xa3, 0x37, 0x81, 0x81, 0x99,
	0x72, 0x95, 0xa8, 0xdf, 0x17, 0xe6, 0xdb, 0x2f, 0xf4, 0x53, 0xdb, 0x7e, 0x0d, 0x9e, 0x4a, 0x0b,
	0x26, 0xf5, 0x82, 0x6d, 0x48, 0x80, 0x97, 0x98, 0x34, 0x16, 0x17, 0x16, 0x37, 0x94, 0x8a, 0x3e,
	0x94, 0x94, 0xa7, 0x94, 0x8c, 0x4c, 0x5b, 0x3c, 0x85, 0xe1, 0x51, 0x85, 0x0f, 0xdd, 0x44, 0xe5,
	0x8d, 0x9e, 0x0f, 0xdd, 0x8c, 0x56, 0xb5, 0x5c, 0xbc, 0x84, 0x13, 0x3b, 0x6e, 0x00, 0xee, 0x3e,
	0xd9, 0x95, 0xd6, 0x96, 0x07, 0x8e, 0x5d, 0xe7, 0x3b, 0x18, 0xd6, 0x2e, 0x6e, 0xcb, 0xd5, 0x96,
	0x1e, 0xd0, 0x9b, 0x3f, 0xbf, 0x38, 0x32, 0x72, 0x5b, 0xae, 0x6e, 0xe8, 0xa1, 0x3e, 0x65, 0x9c,
	0xc2, 0xf9, 0xb3, 0x0f, 0x2f, 0x1b, 0x31, 0x37, 0x2c, 0xe8, 0xc3, 0x82, 0x6d, 0x14, 0xd2, 0xbb,
	0xb8, 0x16, 0x93, 0x84, 0x00, 0x9f, 0x4f, 0xc1, 0x4b, 0xd6, 0xeb, 0x82, 0x2a, 0x45, 0x15, 0xde,
	0xca, 0x8b, 0x7f, 0x3a, 0xe0, 0x62, 0xc6, 0xc3, 0x11, 0xf4, 0x77, 0x94, 0x6f, 0x74, 0x86, 0xc4,
	0x41, 0xdb, 0xea, 0x5b, 0x22, 0xbc, 0xe0, 0xb0, 0x09, 0x35, 0x30, 0xce, 0x69, 0x71, 0x8f, 0x58,
	0x60, 0x77, 0xae, 0x8c, 0x30, 0xf2, 0x1a, 0x36, 0xc6, 0x65, 0xa9, 0x15, 0x19, 0xe3, 0x77, 0x04,
	0x27, 0xa2, 0xd4, 0x08, 0x4c, 0x30, 0x24, 0xe3, 0xf6, 0xdf, 0xf5, 0x05, 0x71, 0xd3, 0x51, 0xf2,
	0x2d, 0x17, 0x8f, 0x78, 0xed, 0x41, 0x9d, 0x64, 0x4c, 0x09, 0x5d, 0x93, 0xff, 0x10, 0x1a, 0x41,
	0x3f, 0xa3, 0x6c, 0x93, 0x69, 0x8c, 0x72, 0x2f, 0xfe, 0x04, 0xfe, 0x53, 0x06, 0xeb, 0xb1, 0xcd,
	0x73, 0x33, 0x6c, 0xb3, 0x9c, 0x00, 0x5c, 0x13, 0x1a, 0xd5, 0xcc, 0x10, 0x80, 0x9b, 0x89, 0xb2,
	0x50, 0x68, 0xbf, 0xf7, 0x2b, 0x00, 0x00, 0xff, 0xff, 0x13, 0x7d, 0x20, 0xd3, 0xda, 0x04, 0x00,
	0x00,
}
