// Code generated by protoc-gen-go.
// source: pp.utxo.proto
// DO NOT EDIT!

package pp

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type GetUtxoReq struct {
	CoinType         *string  `protobuf:"bytes,1,opt,name=coin_type" json:"coin_type,omitempty"`
	Addresses        []string `protobuf:"bytes,10,rep,name=addresses" json:"addresses,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *GetUtxoReq) Reset()                    { *m = GetUtxoReq{} }
func (m *GetUtxoReq) String() string            { return proto.CompactTextString(m) }
func (*GetUtxoReq) ProtoMessage()               {}
func (*GetUtxoReq) Descriptor() ([]byte, []int) { return fileDescriptor9, []int{0} }

func (m *GetUtxoReq) GetCoinType() string {
	if m != nil && m.CoinType != nil {
		return *m.CoinType
	}
	return ""
}

func (m *GetUtxoReq) GetAddresses() []string {
	if m != nil {
		return m.Addresses
	}
	return nil
}

type BtcUtxo struct {
	Address          *string `protobuf:"bytes,10,opt,name=address" json:"address,omitempty"`
	Txid             *string `protobuf:"bytes,11,opt,name=txid" json:"txid,omitempty"`
	Vout             *uint32 `protobuf:"varint,12,opt,name=vout" json:"vout,omitempty"`
	ScriptPubkey     *string `protobuf:"bytes,13,opt,name=script_pubkey" json:"script_pubkey,omitempty"`
	Amount           *uint64 `protobuf:"varint,14,opt,name=amount" json:"amount,omitempty"`
	Confirms         *uint64 `protobuf:"varint,15,opt,name=confirms" json:"confirms,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *BtcUtxo) Reset()                    { *m = BtcUtxo{} }
func (m *BtcUtxo) String() string            { return proto.CompactTextString(m) }
func (*BtcUtxo) ProtoMessage()               {}
func (*BtcUtxo) Descriptor() ([]byte, []int) { return fileDescriptor9, []int{1} }

func (m *BtcUtxo) GetAddress() string {
	if m != nil && m.Address != nil {
		return *m.Address
	}
	return ""
}

func (m *BtcUtxo) GetTxid() string {
	if m != nil && m.Txid != nil {
		return *m.Txid
	}
	return ""
}

func (m *BtcUtxo) GetVout() uint32 {
	if m != nil && m.Vout != nil {
		return *m.Vout
	}
	return 0
}

func (m *BtcUtxo) GetScriptPubkey() string {
	if m != nil && m.ScriptPubkey != nil {
		return *m.ScriptPubkey
	}
	return ""
}

func (m *BtcUtxo) GetAmount() uint64 {
	if m != nil && m.Amount != nil {
		return *m.Amount
	}
	return 0
}

func (m *BtcUtxo) GetConfirms() uint64 {
	if m != nil && m.Confirms != nil {
		return *m.Confirms
	}
	return 0
}

type SkyUtxo struct {
	Hash             *string `protobuf:"bytes,10,opt,name=hash" json:"hash,omitempty"`
	SrcTx            *string `protobuf:"bytes,11,opt,name=src_tx" json:"src_tx,omitempty"`
	Address          *string `protobuf:"bytes,12,opt,name=address" json:"address,omitempty"`
	Coins            *uint64 `protobuf:"varint,13,opt,name=coins" json:"coins,omitempty"`
	Hours            *uint64 `protobuf:"varint,14,opt,name=hours" json:"hours,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *SkyUtxo) Reset()                    { *m = SkyUtxo{} }
func (m *SkyUtxo) String() string            { return proto.CompactTextString(m) }
func (*SkyUtxo) ProtoMessage()               {}
func (*SkyUtxo) Descriptor() ([]byte, []int) { return fileDescriptor9, []int{2} }

func (m *SkyUtxo) GetHash() string {
	if m != nil && m.Hash != nil {
		return *m.Hash
	}
	return ""
}

func (m *SkyUtxo) GetSrcTx() string {
	if m != nil && m.SrcTx != nil {
		return *m.SrcTx
	}
	return ""
}

func (m *SkyUtxo) GetAddress() string {
	if m != nil && m.Address != nil {
		return *m.Address
	}
	return ""
}

func (m *SkyUtxo) GetCoins() uint64 {
	if m != nil && m.Coins != nil {
		return *m.Coins
	}
	return 0
}

func (m *SkyUtxo) GetHours() uint64 {
	if m != nil && m.Hours != nil {
		return *m.Hours
	}
	return 0
}

type GetUtxoRes struct {
	Result           *Result    `protobuf:"bytes,1,opt,name=result" json:"result,omitempty"`
	BtcUtxos         []*BtcUtxo `protobuf:"bytes,11,rep,name=btc_utxos" json:"btc_utxos,omitempty"`
	SkyUtxos         []*SkyUtxo `protobuf:"bytes,12,rep,name=sky_utxos" json:"sky_utxos,omitempty"`
	XXX_unrecognized []byte     `json:"-"`
}

func (m *GetUtxoRes) Reset()                    { *m = GetUtxoRes{} }
func (m *GetUtxoRes) String() string            { return proto.CompactTextString(m) }
func (*GetUtxoRes) ProtoMessage()               {}
func (*GetUtxoRes) Descriptor() ([]byte, []int) { return fileDescriptor9, []int{3} }

func (m *GetUtxoRes) GetResult() *Result {
	if m != nil {
		return m.Result
	}
	return nil
}

func (m *GetUtxoRes) GetBtcUtxos() []*BtcUtxo {
	if m != nil {
		return m.BtcUtxos
	}
	return nil
}

func (m *GetUtxoRes) GetSkyUtxos() []*SkyUtxo {
	if m != nil {
		return m.SkyUtxos
	}
	return nil
}

func init() {
	proto.RegisterType((*GetUtxoReq)(nil), "pp.GetUtxoReq")
	proto.RegisterType((*BtcUtxo)(nil), "pp.BtcUtxo")
	proto.RegisterType((*SkyUtxo)(nil), "pp.SkyUtxo")
	proto.RegisterType((*GetUtxoRes)(nil), "pp.GetUtxoRes")
}

func init() { proto.RegisterFile("pp.utxo.proto", fileDescriptor9) }

var fileDescriptor9 = []byte{
	// 283 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x4c, 0x90, 0x31, 0x6f, 0xb3, 0x30,
	0x10, 0x86, 0xc5, 0x17, 0xbe, 0xa4, 0x1c, 0x90, 0xb4, 0x96, 0x2a, 0x59, 0x19, 0x22, 0xc4, 0xc4,
	0xc4, 0x90, 0x9f, 0xd0, 0xa5, 0x7b, 0xaa, 0x76, 0x45, 0x89, 0xe3, 0x0a, 0x94, 0x82, 0xaf, 0xbe,
	0x73, 0x05, 0xff, 0xbe, 0xb2, 0x43, 0xd4, 0x8c, 0x7e, 0xde, 0xb3, 0x9e, 0x7b, 0x0f, 0x72, 0xc4,
	0xda, 0xf1, 0x68, 0x6a, 0xb4, 0x86, 0x8d, 0xf8, 0x87, 0xb8, 0xdd, 0x20, 0xd6, 0xca, 0xf4, 0xbd,
	0x19, 0xae, 0xb0, 0xdc, 0x03, 0xbc, 0x6a, 0x7e, 0xe7, 0xd1, 0x1c, 0xf4, 0xb7, 0x78, 0x82, 0x44,
	0x99, 0x6e, 0x68, 0x78, 0x42, 0x2d, 0xa3, 0x22, 0xaa, 0x12, 0x8f, 0x8e, 0xe7, 0xb3, 0xd5, 0x44,
	0x9a, 0x24, 0x14, 0x8b, 0x2a, 0x29, 0x0d, 0xac, 0x5e, 0x58, 0xf9, 0x3f, 0x62, 0x03, 0xab, 0x39,
	0x95, 0x10, 0xc6, 0x33, 0x88, 0x79, 0xec, 0xce, 0x32, 0xbd, 0xbd, 0x7e, 0x8c, 0x63, 0x99, 0x15,
	0x51, 0x95, 0x8b, 0x67, 0xc8, 0x49, 0xd9, 0x0e, 0xb9, 0x41, 0x77, 0xba, 0xe8, 0x49, 0xe6, 0x61,
	0x68, 0x0d, 0xcb, 0x63, 0x6f, 0xdc, 0xc0, 0x72, 0x5d, 0x44, 0x55, 0x2c, 0x1e, 0xe1, 0x41, 0x99,
	0xe1, 0xb3, 0xb3, 0x3d, 0xc9, 0x8d, 0x27, 0xe5, 0x07, 0xac, 0xde, 0x2e, 0x53, 0x10, 0x66, 0x10,
	0xb7, 0x47, 0x6a, 0x67, 0xdb, 0x1a, 0x96, 0x64, 0x55, 0xc3, 0xe3, 0xec, 0xbb, 0x5b, 0x27, 0x0b,
	0x20, 0x87, 0xff, 0xbe, 0x10, 0x05, 0x55, 0xec, 0x9f, 0xad, 0x71, 0x96, 0xae, 0xa6, 0xb2, 0xbd,
	0x2b, 0x4f, 0x62, 0x0b, 0x4b, 0xab, 0xc9, 0x7d, 0x71, 0x68, 0x9e, 0xee, 0xa1, 0x46, 0xac, 0x0f,
	0x81, 0x88, 0x1d, 0x24, 0x27, 0x56, 0x8d, 0xbf, 0x26, 0xc9, 0xb4, 0x58, 0x54, 0xe9, 0x3e, 0xf5,
	0xf1, 0xed, 0x0e, 0x3b, 0x48, 0xe8, 0x32, 0xcd, 0x79, 0xf6, 0x97, 0xcf, 0x6b, 0xff, 0x06, 0x00,
	0x00, 0xff, 0xff, 0x28, 0xc1, 0x07, 0xb6, 0x8b, 0x01, 0x00, 0x00,
}
