// Code generated by protoc-gen-go.
// source: pp.utxo.proto
// DO NOT EDIT!

package pp

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type GetUtxoReq struct {
	CoinType         *string  `protobuf:"bytes,1,opt,name=coin_type" json:"coin_type,omitempty"`
	Addresses        []string `protobuf:"bytes,10,rep,name=addresses" json:"addresses,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *GetUtxoReq) Reset()                    { *m = GetUtxoReq{} }
func (m *GetUtxoReq) String() string            { return proto.CompactTextString(m) }
func (*GetUtxoReq) ProtoMessage()               {}
func (*GetUtxoReq) Descriptor() ([]byte, []int) { return fileDescriptor9, []int{0} }

func (m *GetUtxoReq) GetCoinType() string {
	if m != nil && m.CoinType != nil {
		return *m.CoinType
	}
	return ""
}

func (m *GetUtxoReq) GetAddresses() []string {
	if m != nil {
		return m.Addresses
	}
	return nil
}

type GetUtxoRes struct {
	CoinType         *string `protobuf:"bytes,1,opt,name=coin_type" json:"coin_type,omitempty"`
	Utxos            *string `protobuf:"bytes,10,opt,name=utxos" json:"utxos,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *GetUtxoRes) Reset()                    { *m = GetUtxoRes{} }
func (m *GetUtxoRes) String() string            { return proto.CompactTextString(m) }
func (*GetUtxoRes) ProtoMessage()               {}
func (*GetUtxoRes) Descriptor() ([]byte, []int) { return fileDescriptor9, []int{1} }

func (m *GetUtxoRes) GetCoinType() string {
	if m != nil && m.CoinType != nil {
		return *m.CoinType
	}
	return ""
}

func (m *GetUtxoRes) GetUtxos() string {
	if m != nil && m.Utxos != nil {
		return *m.Utxos
	}
	return ""
}

func init() {
	proto.RegisterType((*GetUtxoReq)(nil), "pp.GetUtxoReq")
	proto.RegisterType((*GetUtxoRes)(nil), "pp.GetUtxoRes")
}

func init() { proto.RegisterFile("pp.utxo.proto", fileDescriptor9) }

var fileDescriptor9 = []byte{
	// 108 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xe2, 0xe2, 0x2d, 0x28, 0xd0, 0x2b,
	0x2d, 0xa9, 0xc8, 0xd7, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x2a, 0x28, 0x50, 0x32, 0xe2,
	0xe2, 0x72, 0x4f, 0x2d, 0x09, 0x05, 0x0a, 0x06, 0xa5, 0x16, 0x0a, 0x09, 0x72, 0x71, 0x26, 0xe7,
	0x67, 0xe6, 0xc5, 0x97, 0x54, 0x16, 0xa4, 0x4a, 0x30, 0x2a, 0x30, 0x6a, 0x70, 0x82, 0x84, 0x12,
	0x53, 0x52, 0x8a, 0x52, 0x8b, 0x8b, 0x53, 0x8b, 0x25, 0xb8, 0x14, 0x98, 0x35, 0x38, 0x95, 0xf4,
	0x90, 0xf4, 0x14, 0x63, 0xd3, 0xc3, 0xcb, 0xc5, 0x0a, 0xb2, 0x06, 0xa4, 0x1e, 0xc8, 0x05, 0x04,
	0x00, 0x00, 0xff, 0xff, 0xbb, 0xb9, 0x60, 0x8a, 0x77, 0x00, 0x00, 0x00,
}
