// Code generated by protoc-gen-go.
// source: pp.utxo.proto
// DO NOT EDIT!

package pp

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type GetUtxoReq struct {
	CoinType         *string  `protobuf:"bytes,1,opt,name=coin_type" json:"coin_type,omitempty"`
	Addresses        []string `protobuf:"bytes,10,rep,name=addresses" json:"addresses,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *GetUtxoReq) Reset()                    { *m = GetUtxoReq{} }
func (m *GetUtxoReq) String() string            { return proto.CompactTextString(m) }
func (*GetUtxoReq) ProtoMessage()               {}
func (*GetUtxoReq) Descriptor() ([]byte, []int) { return fileDescriptor9, []int{0} }

func (m *GetUtxoReq) GetCoinType() string {
	if m != nil && m.CoinType != nil {
		return *m.CoinType
	}
	return ""
}

func (m *GetUtxoReq) GetAddresses() []string {
	if m != nil {
		return m.Addresses
	}
	return nil
}

type BtcUtxo struct {
	Address          *string `protobuf:"bytes,10,opt,name=address" json:"address,omitempty"`
	Txid             *string `protobuf:"bytes,11,opt,name=txid" json:"txid,omitempty"`
	Vout             *uint32 `protobuf:"varint,12,opt,name=vout" json:"vout,omitempty"`
	ScriptPubkey     *string `protobuf:"bytes,13,opt,name=script_pubkey" json:"script_pubkey,omitempty"`
	Amount           *uint64 `protobuf:"varint,14,opt,name=amount" json:"amount,omitempty"`
	Confirms         *uint64 `protobuf:"varint,15,opt,name=confirms" json:"confirms,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *BtcUtxo) Reset()                    { *m = BtcUtxo{} }
func (m *BtcUtxo) String() string            { return proto.CompactTextString(m) }
func (*BtcUtxo) ProtoMessage()               {}
func (*BtcUtxo) Descriptor() ([]byte, []int) { return fileDescriptor9, []int{1} }

func (m *BtcUtxo) GetAddress() string {
	if m != nil && m.Address != nil {
		return *m.Address
	}
	return ""
}

func (m *BtcUtxo) GetTxid() string {
	if m != nil && m.Txid != nil {
		return *m.Txid
	}
	return ""
}

func (m *BtcUtxo) GetVout() uint32 {
	if m != nil && m.Vout != nil {
		return *m.Vout
	}
	return 0
}

func (m *BtcUtxo) GetScriptPubkey() string {
	if m != nil && m.ScriptPubkey != nil {
		return *m.ScriptPubkey
	}
	return ""
}

func (m *BtcUtxo) GetAmount() uint64 {
	if m != nil && m.Amount != nil {
		return *m.Amount
	}
	return 0
}

func (m *BtcUtxo) GetConfirms() uint64 {
	if m != nil && m.Confirms != nil {
		return *m.Confirms
	}
	return 0
}

type SkyUtxo struct {
	Hash             *string `protobuf:"bytes,10,opt,name=hash" json:"hash,omitempty"`
	SrcTx            *string `protobuf:"bytes,11,opt,name=src_tx" json:"src_tx,omitempty"`
	Address          *string `protobuf:"bytes,12,opt,name=address" json:"address,omitempty"`
	Coins            *uint64 `protobuf:"varint,13,opt,name=coins" json:"coins,omitempty"`
	Hours            *uint64 `protobuf:"varint,14,opt,name=hours" json:"hours,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *SkyUtxo) Reset()                    { *m = SkyUtxo{} }
func (m *SkyUtxo) String() string            { return proto.CompactTextString(m) }
func (*SkyUtxo) ProtoMessage()               {}
func (*SkyUtxo) Descriptor() ([]byte, []int) { return fileDescriptor9, []int{2} }

func (m *SkyUtxo) GetHash() string {
	if m != nil && m.Hash != nil {
		return *m.Hash
	}
	return ""
}

func (m *SkyUtxo) GetSrcTx() string {
	if m != nil && m.SrcTx != nil {
		return *m.SrcTx
	}
	return ""
}

func (m *SkyUtxo) GetAddress() string {
	if m != nil && m.Address != nil {
		return *m.Address
	}
	return ""
}

func (m *SkyUtxo) GetCoins() uint64 {
	if m != nil && m.Coins != nil {
		return *m.Coins
	}
	return 0
}

func (m *SkyUtxo) GetHours() uint64 {
	if m != nil && m.Hours != nil {
		return *m.Hours
	}
	return 0
}

type GetUtxoRes struct {
	Result           *Result    `protobuf:"bytes,1,opt,name=result" json:"result,omitempty"`
	BtcUtxos         []*BtcUtxo `protobuf:"bytes,11,rep,name=btc_utxos" json:"btc_utxos,omitempty"`
	SkyUtxos         []*SkyUtxo `protobuf:"bytes,12,rep,name=sky_utxos" json:"sky_utxos,omitempty"`
	XXX_unrecognized []byte     `json:"-"`
}

func (m *GetUtxoRes) Reset()                    { *m = GetUtxoRes{} }
func (m *GetUtxoRes) String() string            { return proto.CompactTextString(m) }
func (*GetUtxoRes) ProtoMessage()               {}
func (*GetUtxoRes) Descriptor() ([]byte, []int) { return fileDescriptor9, []int{3} }

func (m *GetUtxoRes) GetResult() *Result {
	if m != nil {
		return m.Result
	}
	return nil
}

func (m *GetUtxoRes) GetBtcUtxos() []*BtcUtxo {
	if m != nil {
		return m.BtcUtxos
	}
	return nil
}

func (m *GetUtxoRes) GetSkyUtxos() []*SkyUtxo {
	if m != nil {
		return m.SkyUtxos
	}
	return nil
}

func init() {
	proto.RegisterType((*GetUtxoReq)(nil), "pp.GetUtxoReq")
	proto.RegisterType((*BtcUtxo)(nil), "pp.BtcUtxo")
	proto.RegisterType((*SkyUtxo)(nil), "pp.SkyUtxo")
	proto.RegisterType((*GetUtxoRes)(nil), "pp.GetUtxoRes")
}

func init() { proto.RegisterFile("pp.utxo.proto", fileDescriptor9) }

var fileDescriptor9 = []byte{
	// 277 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x4c, 0x90, 0x31, 0x6f, 0xc2, 0x30,
	0x10, 0x85, 0x45, 0xa1, 0xd0, 0x1c, 0x09, 0xb4, 0x96, 0x2a, 0x59, 0x0c, 0x15, 0xca, 0xc4, 0xc4,
	0xc0, 0x4f, 0xe8, 0xd2, 0x9d, 0xaa, 0x5d, 0x23, 0x70, 0x5c, 0x25, 0x4a, 0x13, 0xbb, 0xbe, 0x73,
	0x95, 0xfc, 0xfb, 0x9e, 0x4d, 0x50, 0x19, 0xdf, 0xfb, 0xee, 0xfc, 0x7c, 0x0f, 0x32, 0x6b, 0xf7,
	0x9e, 0x7a, 0xb3, 0xb7, 0xce, 0x90, 0x11, 0x77, 0xd6, 0x6e, 0xd6, 0x6c, 0x29, 0xd3, 0xb6, 0xa6,
	0xbb, 0x98, 0xf9, 0x01, 0xe0, 0x4d, 0xd3, 0x07, 0x4f, 0x1d, 0xf5, 0x8f, 0x78, 0x82, 0x44, 0x99,
	0xba, 0x2b, 0x68, 0xb0, 0x5a, 0x4e, 0xb6, 0x93, 0x5d, 0x12, 0xac, 0x53, 0x59, 0x3a, 0x8d, 0xa8,
	0x51, 0xc2, 0x76, 0xba, 0x4b, 0x72, 0x03, 0x8b, 0x57, 0x52, 0x61, 0x47, 0xac, 0x61, 0x31, 0x52,
	0x66, 0x61, 0x3c, 0x85, 0x19, 0xf5, 0x75, 0x29, 0x97, 0x57, 0xf5, 0x6b, 0x3c, 0xc9, 0x94, 0x55,
	0x26, 0x9e, 0x21, 0x43, 0xe5, 0x6a, 0x4b, 0x85, 0xf5, 0xe7, 0x46, 0x0f, 0x32, 0x8b, 0x43, 0x2b,
	0x98, 0x9f, 0x5a, 0xe3, 0x3b, 0x92, 0x2b, 0xd6, 0x33, 0xf1, 0x08, 0x0f, 0xca, 0x74, 0x5f, 0xb5,
	0x6b, 0x51, 0xae, 0x83, 0x93, 0x7f, 0xc2, 0xe2, 0xbd, 0x19, 0x62, 0x20, 0xbf, 0x58, 0x9d, 0xb0,
	0x1a, 0xd3, 0x78, 0x15, 0x9d, 0x2a, 0xa8, 0x1f, 0xf3, 0x6e, 0xbe, 0x93, 0x46, 0x23, 0x83, 0xfb,
	0x70, 0x10, 0xc6, 0xa8, 0x59, 0x90, 0x95, 0xf1, 0x0e, 0x2f, 0x49, 0x79, 0x75, 0x73, 0x3c, 0x8a,
	0x0d, 0xcc, 0x79, 0xd3, 0x7f, 0x53, 0xbc, 0x7c, 0x79, 0x80, 0x3d, 0x97, 0x75, 0x8c, 0x8e, 0x78,
	0x81, 0xe4, 0x4c, 0xaa, 0x08, 0x6d, 0x22, 0x67, 0x4d, 0x19, 0x2f, 0x03, 0xbe, 0xf6, 0xc0, 0x1c,
	0x9b, 0x61, 0xe4, 0xe9, 0x3f, 0x1f, 0xbf, 0xfd, 0x17, 0x00, 0x00, 0xff, 0xff, 0x28, 0xc1, 0x07,
	0xb6, 0x8b, 0x01, 0x00, 0x00,
}
