// Code generated by protoc-gen-go.
// source: pp.withdrawal.proto
// DO NOT EDIT!

package pp

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type WithdrawalReq struct {
	Pubkey           *string `protobuf:"bytes,10,opt,name=pubkey" json:"pubkey,omitempty"`
	CoinType         *string `protobuf:"bytes,11,opt,name=coin_type" json:"coin_type,omitempty"`
	Coins            *uint64 `protobuf:"varint,12,opt,name=coins" json:"coins,omitempty"`
	OutputAddress    *string `protobuf:"bytes,13,opt,name=output_address" json:"output_address,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *WithdrawalReq) Reset()                    { *m = WithdrawalReq{} }
func (m *WithdrawalReq) String() string            { return proto.CompactTextString(m) }
func (*WithdrawalReq) ProtoMessage()               {}
func (*WithdrawalReq) Descriptor() ([]byte, []int) { return fileDescriptor4, []int{0} }

func (m *WithdrawalReq) GetPubkey() string {
	if m != nil && m.Pubkey != nil {
		return *m.Pubkey
	}
	return ""
}

func (m *WithdrawalReq) GetCoinType() string {
	if m != nil && m.CoinType != nil {
		return *m.CoinType
	}
	return ""
}

func (m *WithdrawalReq) GetCoins() uint64 {
	if m != nil && m.Coins != nil {
		return *m.Coins
	}
	return 0
}

func (m *WithdrawalReq) GetOutputAddress() string {
	if m != nil && m.OutputAddress != nil {
		return *m.OutputAddress
	}
	return ""
}

type WithdrawalRes struct {
	Result           *Result `protobuf:"bytes,1,req,name=result" json:"result,omitempty"`
	NewTxid          *string `protobuf:"bytes,20,opt,name=new_txid" json:"new_txid,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *WithdrawalRes) Reset()                    { *m = WithdrawalRes{} }
func (m *WithdrawalRes) String() string            { return proto.CompactTextString(m) }
func (*WithdrawalRes) ProtoMessage()               {}
func (*WithdrawalRes) Descriptor() ([]byte, []int) { return fileDescriptor4, []int{1} }

func (m *WithdrawalRes) GetResult() *Result {
	if m != nil {
		return m.Result
	}
	return nil
}

func (m *WithdrawalRes) GetNewTxid() string {
	if m != nil && m.NewTxid != nil {
		return *m.NewTxid
	}
	return ""
}

func init() {
	proto.RegisterType((*WithdrawalReq)(nil), "pp.WithdrawalReq")
	proto.RegisterType((*WithdrawalRes)(nil), "pp.WithdrawalRes")
}

func init() { proto.RegisterFile("pp.withdrawal.proto", fileDescriptor4) }

var fileDescriptor4 = []byte{
	// 180 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x54, 0xce, 0x41, 0xcb, 0x82, 0x40,
	0x10, 0x06, 0x60, 0x94, 0xef, 0x93, 0x1c, 0xd3, 0x6a, 0x8b, 0x58, 0x3c, 0x89, 0x27, 0x4f, 0x1e,
	0xba, 0xf7, 0x27, 0xbc, 0x44, 0x27, 0x31, 0x77, 0x21, 0x49, 0xdd, 0xc9, 0x9d, 0xc5, 0xfc, 0xf7,
	0xad, 0x06, 0x41, 0xc7, 0x79, 0xde, 0x77, 0x86, 0x81, 0x3d, 0x62, 0x3e, 0x36, 0x74, 0x17, 0x43,
	0x35, 0x56, 0x6d, 0x8e, 0x83, 0x22, 0xc5, 0x5c, 0xc4, 0x78, 0x63, 0x83, 0x5a, 0x75, 0x9d, 0xea,
	0x3f, 0x98, 0x5e, 0x21, 0xbc, 0x7c, 0x8b, 0x85, 0x7c, 0xb2, 0x08, 0x3c, 0x34, 0xb7, 0x87, 0x9c,
	0x38, 0x24, 0x4e, 0xe6, 0xb3, 0x1d, 0xf8, 0xb5, 0x6a, 0xfa, 0x92, 0x26, 0x94, 0x3c, 0x58, 0x28,
	0x84, 0xff, 0x99, 0x34, 0x5f, 0xdb, 0xf1, 0x8f, 0x1d, 0x21, 0x52, 0x86, 0xd0, 0x50, 0x59, 0x09,
	0x31, 0x48, 0xad, 0x79, 0x38, 0xd7, 0xd2, 0xf3, 0xef, 0x69, 0xcd, 0x62, 0xf0, 0x6c, 0x6c, 0x5a,
	0xe2, 0x4e, 0xe2, 0x66, 0xc1, 0x09, 0x72, 0xfb, 0x4d, 0xb1, 0x08, 0xdb, 0xc2, 0xaa, 0x97, 0x63,
	0x49, 0xaf, 0x46, 0xf0, 0xc3, 0xbc, 0xfe, 0x0e, 0x00, 0x00, 0xff, 0xff, 0x04, 0xf5, 0x53, 0xc7,
	0xc4, 0x00, 0x00, 0x00,
}
